ballerina-platform/openapi-tools

- gradle.properties
- openapi-cli/src/main/java/io/ballerina/generators/BallerinaClientGenerator.java
- openapi-cli/src/main/java/io/ballerina/generators/BallerinaSchemaGenerator.java
- openapi-cli/src/test/java/io/ballerina/generators/client/QueryParameterTests.java
- openapi-cli/src/test/resources/generators/client/ballerina/query_param_with_default_value.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/openapi_weather_api.bal
1. Update `serviceURL` to required parameter when `server url` is not given in the schema
Issue:
```
public isolated function init(ClientConfig clientConfig, string serviceUrl = "/") returns error? {
...
}
```
Solution:
```
public isolated function init(ClientConfig clientConfig, string serviceUrl) returns error? {
....
}
```
2. Remove nullable option when default value is given in a optional parameter
Issue:
```
remote isolated function listMeetings(string? 'type = "live") {
...
}
```
Solution:
```
remote isolated function listMeetings(string 'type = "live") {
...
}
```
3. Fix null pointer issue generating when `type: object` is not given in the open api definition 
Resolves https://github.com/wso2-enterprise/choreo/issues/6498
> Make serviceURL required parameter when client …
> Add minor fixes to beta2

- openapi-cli/src/main/java/io/ballerina/generators/GeneratorUtils.java
> Fix https://github.com/ballerina-platform/ballerina-openapi/issues/376
> Fix json open-api definition file not supporting issue. 

- openapi-cli/src/main/java/io/ballerina/openapi/cmd/CodeGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaClientGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionSignatureGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/BallerinaSchemaGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/ComparedGeneratedFileTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureNodeTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestUtils.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/testcases/BallerinaTestGeneratorTests.java
This reverts commit 930483fea2d01cc253d18cce6f8fbd391eb5dc3c, reversing
changes made to 7cc8ca75f9c7df16f49fd3ede83a8e1f53d6021a.
Conflicts:
> openapi-cli/src/main/java/io/ballerina/openapi/cmd/CodeGenerator.java
> openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaClientGenerator.java
> openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionSignatureGenerator.java
> openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/BallerinaSchemaGenerator.java
> Remove enums from code generation untill following issues get fixed
https://github.com/ballerina-platform/ballerina-spec/issues/830
https://github.com/ballerina-platform/ballerina-lang/issues/31925 …
> Revert "Merge pull request #363 from aneeshafedo/beta2-enum"

- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaClientGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionSignatureGenerator.java
- openapi-cli/src/test/resources/expected_gen/generate_client.bal
- openapi-cli/src/test/resources/expected_gen/generated_client_with_license.bal
- openapi-cli/src/test/resources/generators/client/ballerina/header_param_with_default_value.bal
- openapi-cli/src/test/resources/generators/client/ballerina/header_parameter.bal
- openapi-cli/src/test/resources/generators/client/ballerina/header_without_parameter.bal
- openapi-cli/src/test/resources/generators/client/ballerina/missing_server_url.bal
- openapi-cli/src/test/resources/generators/client/ballerina/query_param_with_default_value.bal
- openapi-cli/src/test/resources/generators/client/ballerina/query_param_with_ref_schema.bal
- openapi-cli/src/test/resources/generators/client/ballerina/query_param_without_default_value.bal
- openapi-cli/src/test/resources/generators/client/ballerina/request_body_allOf_scenarios.bal
- openapi-cli/src/test/resources/generators/client/ballerina/request_body_basic_scenarios.bal
- openapi-cli/src/test/resources/generators/client/ballerina/request_body_oneOf_scenarios.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/openapi_weather_api.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/uber_openapi.bal
$subject
> Select `https` server URL when multiple URLs given - Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/458
> Update header map api key names to a string literal - Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/459
> Remove extra spaces between parameter type and name in util functions - Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/453
> Enable users to access the most secured API endpoint
> Increase the cleanness of the generated code. 
> JDK …
> Add implementation to select `https` server url and update header map key name format

- openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaAuthConfigGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaClientGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaTestGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/auth/HttpAuthTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/auth/OAuth2Tests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestConstants.java
- openapi-cli/src/test/resources/generators/client/ballerina/header_param_with_default_value.bal
- openapi-cli/src/test/resources/generators/client/ballerina/header_parameter.bal
- openapi-cli/src/test/resources/generators/client/ballerina/header_without_parameter.bal
- openapi-cli/src/test/resources/generators/client/ballerina/missing_server_url.bal
- openapi-cli/src/test/resources/generators/client/ballerina/openapi_display_annotation.bal
- openapi-cli/src/test/resources/generators/client/ballerina/query_param_with_default_value.bal
- openapi-cli/src/test/resources/generators/client/ballerina/query_param_with_ref_schema.bal
- openapi-cli/src/test/resources/generators/client/ballerina/query_param_without_default_value.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/bitbucket.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/openapi_weather_api.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/uber_openapi.bal
> $subject
> Alternative approach for the issue https://github.com/ballerina-platform/ballerina-openapi/issues/475
> Enable users to configure more customized connector facilitating high availability.  
> Java JDK 11
> Set common client configurations when initializing the connector

- openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaAuthConfigGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaTestGenerator.java
> $subject
Generated test.bal file 
```
import ballerina/test;
configurable http:BearerTokenConfig & readonly auth = ?;
ClientConfig clientConfig = {auth : auth};
Client baseClient = check new Client(clientConfig);
@test:Config {}
isolated function  testGetAccountPersons() {
}
```
Generated Config.toml file :
```
[authConfig]
token = "<Enter your token here>"
```
`Config.toml` file has `authConfig` record but `test.bal` file search for `auth` record. Results in error
```
error: value not provided for required configurable variable 'auth'
at aneesha/stripe:0.1.0(tests/test.bal:4)
warning: [Config.toml:(1:1,2:46)] unused configuration value 'authConfig'
```
Change `test.bal`'s configurable variable name to `authConfig`
```
import ballerina/test; …
```
> Bug fix for mismatching configurable variable names in tests

- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaAuthConfigGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/uber_openapi.bal
> $subject
> Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/499
When providing authentication via API keys, consider the `security schemes` configured in root level and operation level security sections. 
**Sample OpenAPI definition**
```
openapi: 3.0.0
info:
description: "Client endpoint for the given API"
license:
name: Creative Commons
url: https://creativecommons.org/licenses/by/4.0/legalcode
title: Api2Pdf - PDF Generation, Powered by AWS Lambda
version: 1.0.0
security:
- HeaderApiKey: []
paths:
....
components: 
securitySchemes:
HeaderApiKey:
in: header
name: Authorization
type: apiKey
QueryApiKey:
in: query
name: apikey
type: apiKey
````
**Solution** : Configure only `HeaderApiKey` in each operation
```
remote isolated function chromeFromUrlGET(string url, …
```
> [Client] Add implementation to check security section when providing authentication via API key

- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaClientGenerator.java
- openapi-cli/src/test/resources/expected_gen/generate_client.bal
- openapi-cli/src/test/resources/expected_gen/generated_client_with_license.bal
- openapi-cli/src/test/resources/generators/client/ballerina/client_template.bal
- openapi-cli/src/test/resources/generators/client/ballerina/header_param_with_default_value.bal
- openapi-cli/src/test/resources/generators/client/ballerina/missing_server_url.bal
- openapi-cli/src/test/resources/generators/client/ballerina/openapi_display_annotation.bal
- openapi-cli/src/test/resources/generators/client/ballerina/operation_get.bal
- openapi-cli/src/test/resources/generators/client/ballerina/query_param_with_default_value.bal
- openapi-cli/src/test/resources/generators/client/ballerina/query_param_with_ref_schema.bal
- openapi-cli/src/test/resources/generators/client/ballerina/query_param_without_default_value.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/bitbucket.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/jira_openapi.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/openapi_weather_api.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/uber_openapi.bal
> Remove import ballerina/lang.'string since the packages under `ballerina/lang` automatically get loaded
> [Client] Remove `ballerina/lang.'string` import in client generation 

- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionBodyNodeTests.java
- openapi-cli/src/test/resources/generators/client/diagnostic_files/operation_delete.yaml
> Bug fix
> $subject
Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/480
Sample generated code for http DELETE operations with no request body 
```ballerina
remote isolated function deletePetById(string petId) returns http:Response|error {
string  path = string `/pets/${petId}`;
http:Response response = check self.clientEp-> delete(path, targetType = http:Response);
}
```
> Java JDK 11
> Ubuntu 20.04
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you …
> [Client] Remove unnecessary request initialization in delete operations

- openapi-cli/src/main/java/io/ballerina/openapi/cmd/CodeGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java
- openapi-cli/src/test/resources/no_schema.yaml
> Bug fix 
> $subject
Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/426
> Generated types.bal file only when at least one type is available
- Ran FindSecurityBugs plugin and verified report? yesno - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Java JDK 11, 
> Ubuntu 20.04 LTS
> [Client] Add implementation to generate types.bal only when schemes are given

- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionReturnType.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/BallerinaDiagnosticTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureNodeTests.java
- openapi-cli/src/test/resources/generators/client/diagnostic_files/response_nested_array.yaml
- openapi-cli/src/test/resources/generators/client/swagger/response_nested_array.yaml
- openapi-cli/src/test/resources/generators/client/swagger/response_string_array.yaml
> $subject
Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/430
**Sample OpenAPI definition with 2D inline array as response schema**
```
responses:
"200":
content:
schema:
items:
items:
type: string
type: array
type: array
description: An array of tags
```
**Solution implemented**
```ballerina
public type StringNestedArr string[][];
remote isolated function getTimesTags(string query, string? filter = (), int max = 10) returns string[][]|error {
string  path = string `/timestags`;
map<anydata> queryParam = {"query": query, "filter": filter, "max": max, "api-key": self.apiKeys["api-key"]};
path = path + check getPathForQueryParam(queryParam);
string[][] response = check self.clientEp-> get(path, targetType = StringNestedArr);
}
``` …
> [Client] Provide support for inline two dimensional array in response schemes

- openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/BallerinaSchemaGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/AllOfDataTypeTests.java
- openapi-cli/src/test/resources/generators/schema/ballerina/allOfWithEmptyObject.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/allOfWithNoType.bal
- openapi-cli/src/test/resources/generators/schema/swagger/allOfWithEmptyObject.yaml
- openapi-cli/src/test/resources/generators/schema/swagger/allOfWithNoType.yaml
> $subject
In the current connector generation, record fields are not generated in below scenario
```
Pet:
allOf:
- properties:
id:
type: integer
format: int64
name:
type: string
tag:
type: string
type:
type: string
- properties:
entries:
type: array
items:
type: string
```
The issue is due to not specifying the type in the schemas under allOf schema.  At the times that the type of the schema is not specified but the properties are given, the schema is type: object by default
Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/370
In the above scenario. ballerina code should be generated as below. 
```ballerina
public type Pet record {
int id?;
string name?;
string tag?;
string 'type?;
string[] entries?;
};
``` …
> [Client] Bug fix in record field generation when the type of inline allOf schema in not specified 

- openapi-validator/src/main/java/io/ballerina/openapi/validator/ServiceValidator.java
> Fix #573 
Fix tested with manual distribution pack, integration tests will be added in separate PR for all the validator tasks.
> [Validator] Fix OpenAPI module compiler plugin breaks when the `contract` path is invalid in `openapi:ServiceInfo` annotation

- openapi-cli/src/main/java/io/ballerina/openapi/generators/DocCommentsGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaAuthConfigGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaClientGenerator.java
- openapi-cli/src/test/resources/generators/client/auth/scenarios/api_key/custome_api_key_doc.yaml
- openapi-cli/src/test/resources/generators/client/diagnostic_files/openapi_display_annotation.yaml
- openapi-cli/src/test/resources/generators/client/file_provider/swagger/openapi.yaml
- openapi-cli/src/test/resources/generators/client/file_provider/swagger/openapi_weather_api.yaml
- openapi-cli/src/test/resources/generators/client/file_provider/swagger/playlist.yaml
- openapi-cli/src/test/resources/generators/client/swagger/header_param_with_default_value.yaml
- openapi-cli/src/test/resources/generators/client/swagger/invalid_query_param.yaml
- openapi-cli/src/test/resources/generators/client/swagger/missing_server_url.yaml
- openapi-cli/src/test/resources/generators/client/swagger/openapi_display_annotation.yaml
- openapi-cli/src/test/resources/generators/client/swagger/query_param_with_advance_scenarios.yaml
- openapi-cli/src/test/resources/generators/client/swagger/query_param_with_default_value.yaml
- openapi-cli/src/test/resources/generators/client/swagger/query_param_with_ref_schema.yaml
- openapi-cli/src/test/resources/generators/client/swagger/query_param_without_default_value.yaml
- openapi-cli/src/test/resources/generators/schema/swagger/nullable_null_type.yaml
- openapi-cli/src/test/resources/generators/schema/swagger/nullable_option_null_type.yaml
- openapi-cli/src/test/resources/generators/schema/swagger/nullable_option_string_type.yaml
- openapi-cli/src/test/resources/generators/schema/swagger/nullable_string_type.yaml
- openapi-cli/src/test/resources/generators/schema/swagger/openapi_weather_api.yaml
- openapi-cli/src/test/resources/generators/schema/swagger/schema_referenced_in_parameters.yaml
- openapi-cli/src/test/resources/x_init_description.yaml
> $subject
Rename the extensions that were introduced to include Ballerina related data
`x-display` -> `x-ballerina-display`
`x-init-description` -> `x-ballerina-init-description`
`x-apikey-description` -> `x-ballerina-apikey-description`
> Java JDK 11
> Ubuntu 20.04
> [Client] Rename OpenAPI extension names

- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java
> When there is no query parameter is given in any of the operations, but query parameter api key is defined, relevant util functions to set the query parameters to the http:Request are not generated.  
> Bug fix
> https://github.com/ballerina-platform/ballerina-openapi/pull/562
> [Client] utils.bal file generation bug fix

- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaAuthConfigGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/auth/ApiKeyAuthTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestConstants.java
- openapi-cli/src/test/resources/generators/client/auth/scenarios/api_key/multiline_api_key_desc.yaml
> $subject
Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/617
```
securitySchemes:
apiKey:
description: >
To use API you have to sign up and get your own API key. Unify API accounts have sandbox mode and live mode API keys. 
To change modes just use the appropriate key to get a live or test object. You can find your API keys on the unify settings of your Apideck app.
Your Apideck application_id can also be found on the same page.
Go to Unify to grab your API KEY https://app.apideck.com/unify/api-keys
in: header
name: Authorization
type: apiKey
```
```ballerina
public type ApiKeysConfig record {|
string authorization;
|};
```
- Ran FindSecurityBugs plugin …
> [Client] Fix bug in multi line API key documentation generation

- openapi-cli/src/main/java/io/ballerina/openapi/cmd/CodeGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java
- openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestUtils.java
- openapi-cli/src/test/resources/expected_gen/petstore_schema_type.bal
- openapi-cli/src/test/resources/petstore_type.yaml
Fix #686 
- Integration tests -- added
> Java JDK 11
> [Schema] Fix `type.bal` content when using OpenAPI to Ballerina command to generate both client and service files

- openapi-cli/src/main/java/io/ballerina/openapi/cmd/OpenApiCmd.java
> Remove `exitError`  code from success command execution

- openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/Constants.java
- openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIClientCapabilities.java
- openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIClientCapabilitySetter.java
- openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIConverterService.java
- openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIServerCapabilities.java
- openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIServerCapabilitySetter.java
- openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIServiceConstants.java
> Add LS capability registration.
> Since ballerina sl-beta4, language server extensions are not working unless the capabilities are registered.
> Add LS capability registration

- openapi-validator/src/main/java/io/ballerina/openapi/validator/ServiceValidator.java
> Fix #735 
The below example will give a compiler issue.
```ballerina
import ballerina/openapi;
@openapi:ServiceInfo {
title: "Mock Title",
'version: "1.0.0"
}
service /mTitle on new http:Listener(9090) {
resource function get title() returns string {
return "Hello, World!";
}
}
service /mVersion on new http:Listener(9090) {
resource function get versions() returns string {
return "Hello, World!";
}
}
```
- Unit tests 
>Java JDK 11 
> [OpenAPIValidator] Fix issue with OpenAPI validator plugin has multiple service node

- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaUtilGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionSignatureGenerator.java
- openapi-cli/src/main/resources/templates/utils.bal
- openapi-cli/src/test/resources/expected_gen/utils.bal
- openapi-cli/src/test/resources/generators/client/ballerina/header_optional.bal
- openapi-cli/src/test/resources/generators/client/ballerina/header_parameter.bal
- openapi-cli/src/test/resources/generators/client/swagger/header_optional.yaml
- openapi-cli/src/test/resources/generators/client/swagger/header_parameter.yaml
Support integer, boolean types in request header.
Fixes https://github.com/ballerina-platform/ballerina-openapi/issues/730
- Unit tests 
Added
JDK 11
> [Client] Support integer, boolean types in request header

- .github/workflows/publish-release.yml
- README.md
- module-ballerina-openapi/CompilerPlugin.toml
- module-ballerina-openapi/Package.md
- module-ballerina-openapi/build.gradle
- openapi-validator/src/test/resources/project-based-tests/CompilerPlugin.toml
- settings.gradle
> Change the repository name usage with a new repository name.
> Fix for changing `ballerina-openapi` name usage into `openapi-tools`

- openapi-cli/src/main/java/io/ballerina/openapi/cmd/CodeGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/cmd/OpenApiCmd.java
- openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java
- openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/testcases/BallerinaTestGeneratorTests.java
Added "--with-tests" option to add test files to the generated code.
Fixes https://github.com/ballerina-platform/ballerina-openapi/issues/673
Added new option "--with-tests"
- Unit tests 
> Done
> Done
> JDK 11, Ballerina Swan Lake Beta3
> Add command-line option to generate test cases

- openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionSignatureGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/MimeFactory.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/mime/AllType.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/mime/AnyType.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/mime/CustomType.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/mime/JsonType.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionBodyNodeTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java
- openapi-cli/src/test/resources/generators/client/ballerina/any_types_payload.bal
- openapi-cli/src/test/resources/generators/client/ballerina/vendor_specific_payload.bal
- openapi-cli/src/test/resources/generators/client/swagger/all_types_payload.yaml
- openapi-cli/src/test/resources/generators/client/swagger/any_types_payload.yaml
- openapi-cli/src/test/resources/generators/client/swagger/image_payload.yaml
- openapi-cli/src/test/resources/generators/client/swagger/vendor_specific_payload.yaml
Support `*/*`, `image/*` and vendor specific request MIME type in client request body generation. This is part of https://github.com/ballerina-platform/ballerina-openapi/issues/684 improvement.
Fixes https://github.com/ballerina-platform/openapi-tools/issues/621
Fixes https://github.com/ballerina-platform/openapi-tools/issues/675
- Unit tests 
Added
JDK 11
> [Client] Support `*/*`, `image/*` and vendor specific request MIME type

- openapi-cli/src/main/java/io/ballerina/openapi/cmd/CodeGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RemoteFunctionNameValidationTests.java
> Resolves https://github.com/ballerina-platform/openapi-tools/issues/759
> Following error will be thrown when operations with missing `operationId` are found. 
```
OpenAPI definition has errors: 
OperationId is missing in the resource path: /pets(GET)
OperationId is missing in the resource path: /pets(POST)
```
> Improve error message at missing operation ids

- openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaUtilGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionSignatureGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/MimeFactory.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/mime/MultipartFormData.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/mime/XmlType.java
- openapi-cli/src/main/resources/templates/utils.bal
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionBodyNodeTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureNodeTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/UtilGenerationTests.java
- openapi-cli/src/test/resources/expected_gen/utils.bal
- openapi-cli/src/test/resources/generators/client/ballerina/multipart_formdata.bal
- openapi-cli/src/test/resources/generators/client/swagger/multipart_formdata_custom.yaml
- openapi-cli/src/test/resources/generators/client/swagger/unsupported_request_body.yaml
- openapi-cli/src/test/resources/generators/client/utils/swagger/multipart_formdata.yaml
- openapi-cli/src/test/resources/generators/client/utils/swagger/multipart_formdata_custom.yaml
Support `multipart/form-data` request MIME type in client request body generation. This is part of https://github.com/ballerina-platform/ballerina-openapi/issues/684 improvement.
Fixes https://github.com/ballerina-platform/ballerina-openapi/issues/549
- Unit tests 
Added
https://github.com/ballerina-platform/ballerina-openapi/pull/692
https://github.com/ballerina-platform/ballerina-openapi/pull/731
JDK 11
>  [Client] Support `multipart/form-data` request MIME type

- openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionSignatureGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/MimeFactory.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java
- openapi-cli/src/test/resources/generators/client/ballerina/request_body_without_schema.bal
- openapi-cli/src/test/resources/generators/client/swagger/request_body_without_schema.yaml
> Resolves https://github.com/ballerina-platform/openapi-tools/issues/724
```yaml
/pets:
post:
tags:
- pets
- list
parameters:
- name: limit
in: query
schema:
type: integer
format: int32
requestBody:
description: Pet
content:
application/json: {}
responses:
'200':
description: ''
content:
application/json: {}
```
**Suggested code implementation** 
```bal
remote isolated function listPets(json payload, int? 'limit = ()) returns json|error {
string path = string `/pets`;
map<anydata> queryParam = {"limit": 'limit};
path = path + check getPathForQueryParam(queryParam);
http:Request request = new; …
```
> [Client] Add support when RequestBody given without schema

- openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionReturnTypeGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/BallerinaDiagnosticTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/ComparedGeneratedFileTests.java
- openapi-cli/src/test/resources/generators/client/diagnostic_files/duplicated_response.yaml
- openapi-cli/src/test/resources/generators/client/diagnostic_files/head_operation.yaml
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/duplicated_response.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/nillable_response.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/nillable_union_response.bal
- openapi-cli/src/test/resources/generators/client/file_provider/swagger/duplicated_response.yaml
- openapi-cli/src/test/resources/generators/client/file_provider/swagger/nillable_response.yaml
- openapi-cli/src/test/resources/generators/client/file_provider/swagger/nillable_union_response.yaml
> Consider all the success response scenarios
> Generate a `nillable` response if no content (ex: 204) response is given
> Resolves https://github.com/ballerina-platform/openapi-tools/issues/696
**Scenario 1 - Only 204 response is given**
Sample OpenAPI file
```yaml
/pets:
get:
summary: Get a pet
operationId: getPet
tags:
- pets
responses:
'204':
description: The status information cannot be retrieved for the specified request ID.
content: {}
```
Generated remote function
```bal
remote isolated function getPet() returns http:Response|error {
string path = string `/pets`;
http:Response response = check self.clientEp->get(path);
}
```
**Scenario 2 - 204 response is given along with other success responses**
Sample OpenAPI file
```yaml
/pets:
get:
summary: Get a pet …
```
> [Client] Make target type `nillable` when 204 response is given along with other success responses 

- openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaAuthConfigGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaClientGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/auth/OAuth2Tests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestConstants.java
- openapi-cli/src/test/resources/generators/client/auth/scenarios/oauth2/oauth2_client_credential_without_tokenurl.yaml
- openapi-cli/src/test/resources/generators/client/ballerina/combination_of_apikey_and_http_oauth.bal
- Fix https://github.com/ballerina-platform/openapi-tools/issues/733
> [Client] Add tokenUrl by default for OAuth ClientCredintial

- openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionSignatureGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureNodeTests.java
- openapi-cli/src/test/resources/generators/client/swagger/invalid_array_query_params.yaml
- openapi-cli/src/test/resources/generators/client/swagger/valid_operation.yaml
> Resolves https://github.com/ballerina-platform/openapi-tools/issues/777
1. Throw an error when nested array is given as a query parameter
```yaml
parameters:
- name: offset
in: query
required: true
schema:
type: array
items:
type: array
items: 
type: integer
```
2. Throw an error when array type is not defined in a query parameter
```yml
parameters:
- name: offset
in: query
required: true
schema:
type: array
items: {}
```
> Throw errors when unsupported array types given

- openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/TypeGeneratorUtils.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/RecordTypeGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/OneOfDataTypeTests.java
- openapi-cli/src/test/resources/generators/schema/ballerina/oneOf_with_inline_schemas.bal
- openapi-cli/src/test/resources/generators/schema/swagger/oneOf_with_inline_schemas.yaml
> Fix https://github.com/ballerina-platform/openapi-tools/issues/786
> Generate inline record with proper formatting when oneOf schema has inline object schemas
> Add implementation not to generate doc comments for inline record fields
```yaml
schema:
oneOf:
- type: object
properties:
fieldId:
type: integer
description: Lead Field Id with email address
example: 1
placeholders:
type: object
description: Object with template placeholders
- type: object
properties:
email:
description: Recipient Email
type: string
format: email
example: example@iriscrm.com
name:
description: Recipient Name
type: string
example: John Doe
placeholders:
type: object
description: Object with template placeholders
```
**Before the fix**
```bal
public type EmailsTemplateidBody record{#Lead Field …
```
> [Client ]Bug fix in inline record generation

- openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ParametersGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/service/QueryParameterTests.java
- openapi-cli/src/test/resources/generators/service/ballerina/query/query_13.bal
- openapi-cli/src/test/resources/generators/service/ballerina/query/query_14.bal
- openapi-cli/src/test/resources/generators/service/swagger/query/query_13.yaml
- openapi-cli/src/test/resources/generators/service/swagger/query/query_14.yaml
- Fix query parameter order
- Fix missing quoted marks for defaultable query parameter
- Fix https://github.com/ballerina-platform/openapi-tools/issues/797
- Unit tests - add
> List all JDK versions, operating systems, databases, and browser/versions on …
> [Service] Fix query parameter order in resource function

- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIRequestBodyMapper.java
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RequestBodyTest.java
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/rb_scenario15.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/request_body/rb_scenario15.bal
> Fix #841 
- Unit tests - add …
> [BallerinaToOpenAPI]Add support to generate OAS when request payload has `map<string>` type

- openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/service/BallerinaServiceGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ParametersGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ReturnTypeGenerator.java
- openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceGenerationUtils.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/service/RequestBodyTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ReturnTypeTests.java
- openapi-cli/src/test/resources/generators/service/ballerina/inline_record.bal
- openapi-cli/src/test/resources/generators/service/ballerina/requestBody/oneof_requestBody.bal
- openapi-cli/src/test/resources/generators/service/swagger/inline_record_type_request_response.yaml
- openapi-cli/src/test/resources/generators/service/swagger/requestBody/oneOf_request_body.yaml
> Fix #900 
Current tool generated union type for oneOf schemas, allowing union type will be requested via this [issue](https://github.com/ballerina-platform/ballerina-standard-library/issues/2701) in http module.
We will provide the fix for union type once they provide a fix. Until that we are removing generating union type for service now and adding the type for relevant media type. 
- Unit tests  - add
> Provide high-level …
> [Service] Fix Compilation error for union type payload body in generated service

- openapi-extension-tests/src/test/java/io/ballerina/openapi/extension/OpenApiExtensionTest.java
- openapi-extension/src/main/java/io/ballerina/openapi/extension/doc/OpenApiInfoUpdaterTask.java
> $subject
Related to  [`Conflicting configs for OpenAPI definition returns a duplicate key error #2889`](https://github.com/ballerina-platform/ballerina-standard-library/issues/2889)
> Fix conflicting configs error for `openApiDefinition`

- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ResponseTests.java
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/decimal.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/float.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/response/decimal.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/response/float.bal
> [BallerinaToOpenAPI]Add support for when return type has float and decimal types

- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/DataTypeTests.java
- openapi-cli/src/test/resources/ballerina-to-openapi/data_type/tuple_types.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/tuple_type.yaml
Fix https://github.com/ballerina-platform/openapi-tools/issues/1024
https://github.com/wso2-enterprise/internal-support-ballerina/issues/126
> Given the support for tuple type mapping ballerina to openAPI, in OpenAPI tuples are represent in using array type with oneOf composed schema.
```ballerina
public type Pet record {
int id;
//01 tuple type in record field (including possible data types)
[int, string, decimal, float, User] address;
//02 tuple type in user defined data type
ReturnTypes tuples;
//03 tuple type with nullable enable
[int, decimal]? unionTuple;
};
public type User readonly & record {|
int id;
int age;
|};
public type ReturnTypes readonly & [int, decimal];
service /payloadV on new http:Listener(9090) {
resource function post .(@http:Payload Pet …
```
> [BallerinaToOpenAPI]Add support for tuple type mapping

- module-ballerina-openapi/Package.md
- Replace Slack channel with discord in `module-ballerina-openapi/Package.md`
- https://github.com/ballerina-platform/ballerina-standard-library/issues/3463
> Replace Slack channel with discord in `module-ballerina-openapi/Package.md`

- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionBodyNodeTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java
- openapi-cli/src/test/resources/generators/client/ballerina/any_types_payload.bal
- openapi-cli/src/test/resources/generators/client/swagger/any_type_response.yaml
- openapi-cli/src/test/resources/generators/client/swagger/any_types_payload.yaml
- openapi-cli/src/test/resources/generators/client/swagger/array_response_pdf.yaml
- openapi-cli/src/test/resources/generators/client/swagger/empty_object_responnse.yaml
- openapi-cli/src/test/resources/generators/client/swagger/map_schema_response.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionBodyGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionReturnTypeGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/MimeFactory.java
> $subject
Fixes https://github.com/ballerina-platform/openapi-tools/issues/849 in openapi-tool 1.3.x
**OpenAPI schema**
```yaml
/pets:
post:
summary: Create a pet
operationId: createPet
requestBody:
content:
"*/*":
schema:
type: array
items:
type: string
responses:
'200':
description: Successful operation
content:
'*/*':
example:
summary: Pet Response
```
**Generated remote function**
```bal
#
remote isolated function createPet(http:Request request) returns http:Response|error {
string resourcePath = string `/pets`;
// TODO: Update the request as needed;
http:Response response = check self.clientEp->post(resourcePath, request);
}
```
- Ran FindSecurityBugs …
> [1.3.x] Fix function generation for wildcard (*/*) type request bodies and responses

- openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/FieldGenWithNullableOption.java
- openapi-cli/src/test/resources/expected_gen/nullable_false_types.bal
- openapi-cli/src/test/resources/expected_gen/nullable_types.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/additional_properties_composed_schema.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/additional_properties_negative.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/additional_properties_true.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/constraint/record_field_02.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/nullable_anyof_array_schema.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/nullable_anyof_schema.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/nullable_array.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/nullable_false.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/nullable_option_array_schema.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/nullable_option_primitive_fields.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/nullable_option_record_schema.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/nullable_primitive.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/nullable_record.bal
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/TypeGeneratorUtils.java
- openapi-integration-tests/src/test/resources/schema/array.bal
> Resolves https://github.com/ballerina-platform/openapi-tools/issues/957
> Revamp the code generation when a record field is defined as optional and nullable in a OpenAPI schema
Ex : 
```yaml
Pet:
required:
- id
- name
properties:
id:
type: integer
format: int64
name:
type: string
tag:
type: string
nullable: true
types:
type: string
nullable: true
```
**Previous generation**
```bal
public type Pet record {|
int id;
string name;
string? tag?;
string? types?;
|};
```
**New generation**
```bal
public type Pet record {|
int id;
string name;
string? tag = ();
string? types = ();
|};
```
- Confirmed that this PR doesn't commit any …
> [master] Fix to improve nillable field support in OpenAPI to Ballerina schema generation 

- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionBodyNodeTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureNodeTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java
- openapi-cli/src/test/resources/generators/client/ballerina/multipart_formdata_empty.bal
- openapi-cli/src/test/resources/generators/client/ballerina/unsupported_request_body.bal
- openapi-cli/src/test/resources/generators/client/ballerina/unsupported_text_media_type.bal
- openapi-cli/src/test/resources/generators/client/ballerina/vendor_specific_json.bal
- openapi-cli/src/test/resources/generators/client/swagger/mutipart_formdata_empty.yaml
- openapi-cli/src/test/resources/generators/client/swagger/unsupported_request_body.yaml
- openapi-cli/src/test/resources/generators/client/swagger/unsupported_text_media_type.yaml
- openapi-cli/src/test/resources/generators/client/swagger/vendor_specific_json.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionBodyGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java
> Resolves https://github.com/ballerina-platform/openapi-tools/issues/1121, https://github.com/ballerina-platform/openapi-tools/issues/1148
**OpenAPI sample** 
```yaml
requestBody:
content:
multipart/byteranges:  # This mime is not supported for client generation
schema:
properties:
address:
$ref: "#/components/schemas/customer_adresss"
balance:
type: integer
description: Customer Details
```
**Generated bal code**
```bal
remote isolated function postCustomers(string customer, http:Request request) returns Customer|error {
string resourcePath = string `/v1/customer/${getEncodedUri(customer)}`;
// TODO: Update the request as needed;
Customer response = check self.clientEp->post(resourcePath, request);
}
```
Currently we also generate the remote/resource functions for …
> [master] Revamp default request payload / response mapping in client generation

- openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java
- openapi-cli/src/test/resources/expected_gen/petstore_service_swagger.bal
- openapi-cli/src/test/resources/expected_gen/petstore_wildcard_service.bal
- openapi-cli/src/test/resources/expected_gen/petstore_wildcard_types.bal
- openapi-cli/src/test/resources/generators/service/ballerina/requestBody/oneof_requestBody.bal
- openapi-cli/src/test/resources/generators/service/swagger/wildcard.yaml
- openapi-cli/src/test/resources/petstore_wildcard.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/RequestBodyGenerator.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/628
```yaml
/pets/my:
post:
summary: Create a pet
operationId: createPet
tags:
- pets
requestBody:
description: "Request to add a pet"
content:
'*/*':
schema:
$ref: "#/components/schemas/Pets"
responses:
'200':
description: Successful operation
content:
'*/*':
schema:
type: array
items:
description: "Pet records"
```
**Generated Ballerina resource**
service.bal
```bal
listener http:Listener ep0 = new (80, config = {host: "petstore.openapi.io"});
service /v1 on ep0 {
resource function post pets/my(@http:Payload http:Request request) returns OkAnydata {
}
}
```
types.bal
```bal
public type OkAnydata record {|
*http:Ok;
anydata body;
|};
...
```
> [master] Add wildcard support for service generation

- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionBodyNodeTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureReturnTypeTests.java
- openapi-cli/src/test/resources/generators/client/swagger/return_type/no_response.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java
> Resolves https://github.com/ballerina-platform/openapi-tools/issues/1150
```yaml
/pets:
get:
tags:
- pets
- list
parameters:
- name: limit
in: query
schema:
type: integer
responses: {}
```
**Generated function**
```bal
remote isolated function listPets(int? 'limit = ()) returns http:Response|error {
string resourcePath = string `/pets`;
map<anydata> queryParam = {"limit": 'limit};
resourcePath = resourcePath + check getPathForQueryParam(queryParam);
http:Response response = check self.clientEp->get(resourcePath);
}
``` …
> Support OpenAPI operations with no response

- openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ReturnTypeTests.java
- openapi-cli/src/test/resources/generators/service/ballerina/response/empty_response.bal
- openapi-cli/src/test/resources/generators/service/swagger/response/empty_response.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ReturnTypeGenerator.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1174
```yaml
/pets:
get:
tags:
- pets
- list
parameters:
- name: limit
in: query
schema:
type: integer
format: int32
responses: {}
```
**Generated resource in service**
```bal
resource function get pets(int? 'limit) returns http:Response {
}
```
> Java JDK 11
> [master] Support OpenAPI operations with empty response in service generation

- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionBodyNodeTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureReturnTypeTests.java
- openapi-cli/src/test/resources/generators/client/swagger/return_type/no_response.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java
> Resolves https://github.com/ballerina-platform/openapi-tools/issues/1150 in OpenAPI version 1.3
```yaml
/pets:
get:
tags:
- pets
- list
parameters:
- name: limit
in: query
schema:
type: integer
responses: {}
```
**Generated function**
```bal
remote isolated function listPets(int? 'limit = ()) returns http:Response|error {
string resourcePath = string `/pets`;
map<anydata> queryParam = {"limit": 'limit};
resourcePath = resourcePath + check getPathForQueryParam(queryParam);
http:Response response = check self.clientEp->get(resourcePath);
}
``` …
> [1.3.x] Support OpenAPI operations with no response

- openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ReturnTypeTests.java
- openapi-cli/src/test/resources/generators/service/ballerina/response/empty_response.bal
- openapi-cli/src/test/resources/generators/service/swagger/response/empty_response.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ReturnTypeGenerator.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1174 in OpenAPI version 1.3
```yaml
/pets:
get:
tags:
- pets
- list
parameters:
- name: limit
in: query
schema:
type: integer
format: int32
responses: {}
```
**Generated resource in service**
```bal
resource function get pets(int? 'limit) returns http:Response {
}
```
> Java JDK 11
> [1.3.x] Support OpenAPI operations with empty response in service generation

- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java
- openapi-cli/src/test/resources/generators/client/ballerina/octet_stream_request_payload.bal
- openapi-cli/src/test/resources/generators/client/swagger/octet_stream_request_payload.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java
> Fix #1188 
Old Generated code
```ballerina
#
resource isolated function post user(string payload) returns http:Response|error {
string resourcePath = string `/user`;
http:Request request = new;
request.setPayload(payload, "application/octet-stream");
http:Response response = check self.clientEp->post(resourcePath, request);
}
#
resource isolated function post payment(Pet payload) returns http:Response|error {
string resourcePath = string `/payment`;
http:Request request = new;
request.setPayload(payload, "application/octet-stream");
http:Response response = check self.clientEp->post(resourcePath, request);
}
```
After applying the change 
```ballerina
#
resource isolated function post user(byte[] payload) returns http:Response|error {
string …
```
> [1.4.x]Changed the request Payload type into `byte[]` for MediaType `application/octet-stream` in client generations

- openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/service/RequestBodyTests.java
- openapi-cli/src/test/resources/generators/service/ballerina/requestBody/oneof_requestBody.bal
- openapi-cli/src/test/resources/generators/service/ballerina/requestBody/oneof_request_body_types.bal
- openapi-cli/src/test/resources/generators/service/swagger/requestBody/oneOf_request_body.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/BallerinaServiceGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/RequestBodyGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ServiceGenerationUtils.java
> Fix #https://github.com/ballerina-platform/openapi-tools/issues/909
> Generate service generation with request body has oneOf type
```openapi
/pet:
put:
summary: "scenario 01: Request body is with oneOf schema for application/json"
operationId: putKey
requestBody:
content:
schema:
oneOf:
- $ref: "#/components/schemas/Dog"
- $ref: "#/components/schemas/Cat"
responses:
200:
description: Successful operation.
```
Generated service
```ballerina
public type Cat record {|
string name?;
string kind?;
|};
public type Dog record {|
string name?;
string age?;
|};
public type Pet_body Dog|Cat;
resource function put pet(@http:Payload Pet_body payload) returns http:Ok {
}
```
Note: Here `oneOf` schema has been sent under the component section with the name `Pet_body` in OAS by the …
> [1.4.x] Add support for the handle service generation when requestBody  has `oneOf` schema type

- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java
- openapi-cli/src/test/resources/generators/client/ballerina/multipart_binary.bal
- openapi-cli/src/test/resources/generators/client/swagger/multipart_binary.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java
> Resolves https://github.com/ballerina-platform/openapi-tools/issues/816
Currently only object schemas are supported in multipart/form-data mime type in the openapi-to-client generation. This change will generate default request when any other type schema found with multipart/form-data media type.  
**Scenario 1 :** 
```yaml
requestBody:
description: Pet
content:
multipart/form-data:
schema:
type: string
format: binary
```
**Generation** 
```bal
remote isolated function createPet(http:Request request) returns http:Response|error {
string resourcePath = string `/pets`;
// TODO: Update the request as needed;
http:Response response = check self.clientEp->post(resourcePath, request);
}
```
Scenario 2 
```yaml
requestBody:
description: Pet
content:
multipart/form-data: …
```
> Bug fix in multipart/form-data mime type client generation

- openapi-cli/src/test/java/io/ballerina/openapi/generators/service/RequestBodyTests.java
- openapi-cli/src/test/resources/expected_gen/petstore_service_swagger.bal
- openapi-cli/src/test/resources/generators/service/ballerina/requestBody/any_of.bal
- openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_02_rb.bal
- openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_03_rb.bal
- openapi-cli/src/test/resources/generators/service/ballerina/requestBody/unhandled_media_type.bal
- openapi-cli/src/test/resources/generators/service/ballerina/requestBody/url_encode.bal
- openapi-cli/src/test/resources/generators/service/swagger/requestBody/any_of.yaml
- openapi-cli/src/test/resources/generators/service/swagger/requestBody/multiple_content.yaml
- openapi-cli/src/test/resources/generators/service/swagger/requestBody/unhandled_media_type.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/RequestBodyGenerator.java
> FIx #942 
Changed  form-url-encode mapping record into `map<string>`, due to this issue https://github.com/ballerina-platform/ballerina-standard-library/issues/4090, now it map into `map<string>`
> Through this fix we are generating a union type for the request body if it has multiple content types.
```openapi
/pets:
post:
requestBody:
content:
"application/json":
schema:
$ref: "#components/schemas/Pet"
"application/xml":
schema:
$ref: "#components/schemas/Dog"  
responses: 
"201":
description: OK
```
Generated code
```ballerina
service /petstore/v1 on ep0 {
resource function post pets(@http:Payload Pet|xml payload) returns string {
io:println(payload);
return "correct " + payload.name;
}
}
```
> …
> [1.4.x]Handle multiple mediaType in swagger request body for ballerina service generations

- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java
- openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/BallerinaToOpenAPITests.java
- openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation/Ballerina.toml
- openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation/result.yaml
- openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation/service.bal
- openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_with_base_path/Ballerina.toml
- openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_with_base_path/result.yaml
- openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_with_base_path/service.bal
- openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_without_base_path/Ballerina.toml
- openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_without_base_path/result.yaml
- openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_without_base_path/service_file.bal
> Fix #1212 
Parent PR : https://github.com/ballerina-platform/openapi-tools/pull/1213
Support the below services with non-openapi annotations
```ballerina
@display {
label: "SampleRest2",
id: "SampleRest2-a0419d61-26b8-48ad-8696-3a16c9958522"
}
service /payload on new http:Listener(9090) {
resource function get greeting(string name) returns string|error {
// Send a response back to the caller.
if name is "" {
return error("name should not be empty!");
}
return "Hello, " + name;
}
}
```
> [1.3.x]Fix for OpenAPI spec generation when display annotations are used

- gradle.properties
- openapi-cli/src/test/resources/generators/client/ballerina/path_param_duplicated_name.bal
- openapi-cli/src/test/resources/generators/client/ballerina/path_parameter_valid.bal
- openapi-cli/src/test/resources/generators/client/ballerina/path_parameter_with_special_name.bal
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/multiple_pathparam.bal
- openapi-cli/src/test/resources/generators/client/resource/ballerina/pathParameters.bal
> Ballerina Lang will not consider `version` as keyword along with 2201.5.0(Update 05)
Reference PR : https://github.com/ballerina-platform/ballerina-lang/pull/39840
> [master]Add a fix for changing `'version` into `version` to align with Ballerina Lang changes

- openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/PrimitiveDataTypeTests.java
- openapi-cli/src/test/resources/generators/schema/ballerina/additional_properties_invalid_format.bal
- openapi-cli/src/test/resources/generators/schema/swagger/additional_properties_invalid_format.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/RecordTypeGenerator.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1285
Sample OpenAPI
```yaml
schemas:
Mark:
type: object
additionalProperties:
format: double
type: number
```
Generated record 
```bal
public type Mark record {|
decimal...;
|};
```
> Java JDK 11
> [1.4.x] Bug fix in additional property mapping when invalid number format is given

- openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/AnyOfDataTypeTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/ConstraintTests.java
- openapi-cli/src/test/resources/generators/schema/ballerina/constraint/allow_zero_values_for_number_constraint.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/constraint/invalidAndValidConstraintFieldWithDtaType.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/constraint/invalidConstraintFieldWithDtaType.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/constraint/record_field_02.bal
- openapi-cli/src/test/resources/generators/schema/swagger/constraint/allow_zero_values_for_number_constraint.yaml
- openapi-cli/src/test/resources/generators/schema/swagger/constraint/invalidAndValidConstraintFieldWithDataType.yaml
- openapi-cli/src/test/resources/generators/schema/swagger/constraint/invalidConstraintFieldWithDataType.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/BallerinaTypesGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/TypeGeneratorUtils.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/ArrayTypeGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/RecordTypeGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/TypeGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/UnionTypeGenerator.java
> Fix #https://github.com/ballerina-platform/openapi-tools/issues/1291
Tested below connectors  with the command `bal openapi -i <yaml> --mode client`: 
This need to generate constraint import since now it is support for the integer and numbers to have zero as value
- [powertoolsdeveloper.collections](https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/powertoolsdeveloper.collections)
- [powertoolsdeveloper.data](https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/powertoolsdeveloper.data)
- [powertoolsdeveloper.datetime](https://github.com/ballerina-platform/openapi-connectors/blob/main/openapi/powertoolsdeveloper.datetime/openapi.yml)
- [powertoolsdeveloper.files](https://github.com/ballerina-platform/openapi-connectors/blob/main/openapi/powe …
> [1.4.x] Fix for avoiding unnecessary constraint import generation

- openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/ConstraintTests.java
- openapi-cli/src/test/resources/generators/schema/ballerina/constraint/constraint_with_nullable.bal
- openapi-cli/src/test/resources/generators/schema/swagger/constraint/constraint_with_nullable.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/BallerinaTypesGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/TypeGeneratorUtils.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/ArrayTypeGenerator.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1290
Avoid generating constraints when the type is nullable
Ex:
```yaml
Scores:
type: array
items:
type: number
nullable: true
maxItems: 2
minItems: 2
nullable: true
description: At least one entry should be non-null.
```
**Generated bal type**
```bal
public type Scores decimal[]?;
```
> Java JDK 11
> [1.4.x] Bug fix in nullable constraints

- openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ParameterGeneratorTest.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/service/QueryParameterTests.java
- openapi-cli/src/test/resources/generators/service/ballerina/parameters_with_ref_schema.bal
- openapi-cli/src/test/resources/generators/service/swagger/parameter_with_ref_array_invalid_schema.yaml
- openapi-cli/src/test/resources/generators/service/swagger/parameters_with_invalid_ref_schema.yaml
- openapi-cli/src/test/resources/generators/service/swagger/parameters_with_ref_schema.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/BallerinaServiceGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ParametersGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ServiceDiagnosticMessages.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1331
Example:
```yaml
paths:
/users/meetings:
get:
description: List all the meetings that were scheduled
operationId: listMeetings
parameters:
- description: "Meeting location"
in: query
name: location
schema:
$ref: '#/components/schemas/RoomNo'
responses:
"200":
content:
schema:
$ref: '#/components/schemas/MeetingList'
description: "HTTP Status Code:200. List of meetings returned."
components:
schemas:
RoomNo:
enum:
- R1
- R3
- R5
type: string
nullable: true
```
**Proposed generation**
```bal
public type RoomNo string;
resource function get users/meetings(RoomNo location) {
}
```
- …
> Add support for query params with ref schema in service generation

- gradle.properties
- openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ParameterGeneratorTest.java
- openapi-cli/src/test/resources/expected_gen/petstore_service_swagger.bal
- openapi-cli/src/test/resources/generators/service/ballerina/parameters_with_enum.bal
- openapi-cli/src/test/resources/generators/service/ballerina/parameters_with_nullable_enums.bal
- openapi-cli/src/test/resources/generators/service/ballerina/response/petstore_default.bal
- openapi-cli/src/test/resources/generators/service/swagger/parameters_with_nullable_enums.yaml
- openapi-cli/src/test/resources/generators/service/swagger/path_param_nullable.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ParametersGenerator.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1338
Enum Generation in parameters in service generation
> JAVA JDK 11
> Support enums in OpenAPI to Ballerina service generation

- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/AllOfResponsesTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureReturnTypeTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/OneOfResponsesTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestUtils.java
> $subject
We are not utilizing the swagger.v3 OpenAPI parser's flatten to structure to simplify the nested and complex data structure in to seperate component schemas. The tests updated here were not using the flattened OpenAPI for generation, which generated types that are not generating when using the tool. 
> Java JDK 11
> [master] Fix the outdated tests in type generation of compund objects

- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/api2pdf.bal
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionReturnTypeGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/PrimitiveTypeGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/RecordTypeGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ParametersGenerator.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ServiceGenerationUtils.java
- openapi-integration-tests/src/test/java/io/ballerina/openapi/TestUtil.java
- openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/ServiceGenerationTests.java
- openapi-integration-tests/src/test/resources/service/return/swagger/unsupported_oas_format.yaml
- openapi-integration-tests/src/test/resources/testng.xml
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1412
> Print a warning meesage when unsupported data format is given in the OpenAPI file
Fix was sent to address the unsupported data type format scenarios by priniting a warning message in the CLI without terminating the generation purpose. The format would not be considered in generation and the type will be used to identify the corresponsing ballerina type.
Ex:
```yaml
components:
schemas:
Pet:
required:
- id
- name
properties:
id:
type: integer
format: int64
price:
type: number
format: currency
name:
type: string
tag:
type: string
type:
type: string
updatedDate:
type: string
format: date
additionalProperties: false
```
**In 2201.5.1 :**
Generation terminated with the error message 
```Error occurred when …
```
> [1.5.x] Handle unsupported data type formats

- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ResponseTests.java
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/rb_scenario09.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/byte.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/response/byte.bal
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1314
> Java JDK 11
> [master] Fix bug when return type is byte[] in OpenAPI spec generation

- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/ComparedGeneratedFileTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureNodeTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/PrimitiveDataTypeTests.java
- openapi-cli/src/test/resources/generators/client/file_provider/ballerina/incorrect_format.bal
- openapi-cli/src/test/resources/generators/client/file_provider/swagger/incorrect_format.yaml
- openapi-cli/src/test/resources/generators/schema/ballerina/invalid_formats.bal
- openapi-cli/src/test/resources/generators/schema/swagger/invalid_formats.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/EnumGenerator.java
- openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/ServiceGenerationTests.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1483
*   Check the format of a schema against the schema type before generating the ballerina type
*   Return unsupported warning only for the formats that are defined in the OpenAPI spec not for the undefined formats
> Java JDK 17
> [master] Revamp format handling when invalid formats given

- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/BallerinaDiagnosticTests.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureNodeTests.java
- openapi-cli/src/test/resources/generators/client/ballerina/request_body_with_ref.bal
- openapi-cli/src/test/resources/generators/diagnostic_files/requestBody_reference_has_inline_object_content_type.yaml
- openapi-cli/src/test/resources/generators/schema/ballerina/schema_with_request_body_ref.bal
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java
Fixes for two issues:
01. Fixes https://github.com/ballerina-platform/openapi-tools/issues/1484
02. This includes the fix for  **microsoft.dynamics365businesscentral** issue
Issue: **microsoft.dynamics365businesscentral** connector was assigning generate json value when it has the requestBody scenario similar to the above issue.
Reason: Given connector's inline object defined without the schema type object.
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guide …
> [master] Fix for handling of inline objects in content type for reusable request bodies

- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ModuleReferenceTests.java
- openapi-cli/src/test/resources/ballerina-to-openapi/constraint/array.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/constraint/array.yaml
- Add support for mapping Ballerina Array constraints to the OpenAPI specification.
- Modify the unit tests to ensure the accuracy & reliability of `@constraint:Array {}` mapping to OpenAPI spec.
- This ensures that Array constraints in Ballerina are accurately reflected in OpenAPI spec.
Resolves: [#4811](https://github.com/ballerina-platform/ballerina-standard-library/issues/4811)
See also: [#4788](https://github.com/ballerina-platform/ballerina-standard-library/issues/4788)
> Improve support `@constraint:Array {}` annotation mapping to OpenAPI Spec

- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/diagnostic/DiagnosticMessages.java
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIRequestBodyMapper.java
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResourceMapper.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RequestBodyTest.java
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/union_type.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/request_body/union_type.bal
> Fix #https://github.com/ballerina-platform/openapi-tools/issues/1536
Fix https://github.com/wso2-enterprise/internal-support-ballerina/issues/443
Implement the union-type mapping for request body in OpenAPI spec generation
> List …
> [1.8.x]Add support for union type request body mapping to Ballerina to OpenAPI spec generation

- openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ParameterGeneratorTest.java
- openapi-cli/src/test/resources/generators/service/ballerina/multiPathParamWithExtensionType.bal
- openapi-cli/src/test/resources/generators/service/swagger/multiPathParamWithExtensionType.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
> Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/4856
Parent issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4850
> [1.8.x] Fix type mismatching when the resource path end with path segment including parameter and extensions 

- gradle.properties
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/diagnostic/DiagnosticMessages.java
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIRequestBodyMapper.java
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResourceMapper.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RequestBodyTest.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ParameterGeneratorTest.java
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/union_type.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/request_body/union_type.bal
- openapi-cli/src/test/resources/generators/service/ballerina/multiPathParamWithExtensionType.bal
- openapi-cli/src/test/resources/generators/service/swagger/multiPathParamWithExtensionType.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
> Sync master with 1.8.x branch

- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIRequestBodyMapper.java
- openapi-cli/src/test/resources/ballerina-to-openapi/ballerina-project/service/snowpeak_request_body.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/snowpeak_request_body_ref.yaml
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4802
> [1.8.x]Fix req body mapping for array type from external module

- openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/TypeFormatTests.java
- openapi-cli/src/test/resources/generators/schema/ballerina/constraint/format_type.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/format/string_formats.bal
- openapi-cli/src/test/resources/generators/schema/swagger/format/string_formats.yaml
- openapi-cli/src/test/resources/testng.xml
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java
> Fix https://github.com/ballerina-platform/ballerina-standard-library/issues/5072
[As per the OAS specification `byte` format ](https://swagger.io/docs/specification/data-models/data-types/#string:~:text=byte%20%E2%80%93%20base64%2Dencoded%20characters%2C%20for%20example%2C%20U3dhZ2dlciByb2Nrcw%3D%3D)of the string type 
>byte – base64-encoded characters, for example, U3dhZ2dlciByb2Nrcw==
should map to the Ballerina string 
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or …
> [1.8.x]Fix for changing the OAS `byte` format from mapping `byte[]` to `string` in the Ballerina type

- gradle.properties
- openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/TypeFormatTests.java
- openapi-cli/src/test/resources/generators/schema/ballerina/constraint/format_type.bal
- openapi-cli/src/test/resources/generators/schema/ballerina/format/string_formats.bal
- openapi-cli/src/test/resources/generators/schema/swagger/format/string_formats.yaml
- openapi-cli/src/test/resources/testng.xml
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java
> Fix https://github.com/ballerina-platform/ballerina-standard-library/issues/5072
[As per the OAS specification `byte` format ](https://swagger.io/docs/specification/data-models/data-types/#string:~:text=byte%20%E2%80%93%20base64%2Dencoded%20characters%2C%20for%20example%2C%20U3dhZ2dlciByb2Nrcw%3D%3D)of the string type 
>byte – base64-encoded characters, for example, U3dhZ2dlciByb2Nrcw==
should map to the Ballerina string 
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or …
> [master]Fix for changing the OAS `byte` format from mapping `byte[]` to `string` in the Ballerina type 

- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java
- openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/DataTypeTests.java
- openapi-cli/src/test/resources/ballerina-to-openapi/data_type/built_in_sub_types_in_record.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/built_in_sub_types_in_record.yaml
>$Subject
Related to: https://github.com/ballerina-platform/ballerina-library/issues/5883
> [Master] Add built-in subtype support in record fields for OAS generation

- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/ServiceToOpenAPIMapper.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/response/ResponseMapperImpl.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/utils/MapperCommonUtils.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/DataTypeTests.java
- openapi-cli/src/test/resources/ballerina-to-openapi/constraint/array.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/constraint/decimalMax.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/constraint/integerMin.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/constraint/record_fieldRec.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/constraint/string.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/data_type/table_types.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/data_type/tuple_types.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/constraint/array.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/constraint/decimalMax.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/constraint/integerMin.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/constraint/record_fieldRec.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/constraint/string.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/table_types.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/tuple_type.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/parameter_annotation/annotated_payload_complex.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/post_method.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario11.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/typeInclusion_01.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/parameter_annotation/annotated_payload_complex.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/post_method.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/record/with_readonly_keyword.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/response/rs_scenario11.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/response/typeInclusion_01.bal
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/5975
> Improve test coverage after restructuring

- openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java
- openapi-cli/src/test/resources/expected_gen/licenses/schema_for_both_service_client.bal
- openapi-cli/src/test/resources/expected_gen/licenses/schema_for_service.bal
- openapi-cli/src/test/resources/expected_gen/licenses/schema_with_user_given_license.bal
- openapi-cli/src/test/resources/expected_gen/licenses/types_for_both_service_client_generations.bal
- openapi-cli/src/test/resources/expected_gen/petstore_schema.bal
- openapi-cli/src/test/resources/expected_gen/petstore_schema_type.bal
- openapi-cli/src/test/resources/expected_gen/petstore_schema_with_license.bal
- openapi-cli/src/test/resources/expected_gen/petstore_wildcard_types.bal
- openapi-cli/src/test/resources/expected_gen/without-data-binding-type.bal
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
- openapi-integration-tests/src/test/resources/service/return/ballerina/multiple_mediatype_for_one_response_code.bal
- openapi-integration-tests/src/test/resources/service/return/ballerina/response_has_inline_record.bal
> Related PR: https://github.com/ballerina-platform/openapi-tools/pull/1578
Fix: https://github.com/ballerina-platform/ballerina-library/issues/5731
This fix will be available with the 2201.8.5 version onwards 
> [1.8.x] Remove unused types from generated `types.bal` in service generation

- gradle.properties
- openapi-extension-tests/src/test/resources/ballerina_sources/sample_8/Ballerina.toml
> https://github.com/ballerina-platform/ballerina-library/issues/5987
> [master] Fix failing openapi http extension test

- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/Constants.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/constraint/ConstraintMapperImpl.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/model/ModuleMemberVisitor.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/response/ResponseMapperImpl.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/response/model/CacheConfigAnnotation.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/response/model/HeaderRecordInfo.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/response/model/ResponseInfo.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/response/utils/CacheHeaderUtils.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/response/utils/StatusCodeErrorUtils.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/response/utils/StatusCodeResponseUtils.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/response/utils/StatusCodeTypeUtils.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/type/RecordTypeMapper.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/type/ReferenceTypeMapper.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/type/TypeMapper.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/type/TypeMapperImpl.java
- ballerina-to-openapi/src/main/java/module-info.java
- gradle.properties
- openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ResponseTests.java
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/post_method.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/readonly.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_with_headers.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/status_code_errors_01.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/status_code_errors_02.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/status_code_errors_03.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/typeInclusion_01.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/response/status_code_errors_01.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/response/status_code_errors_02.bal
- openapi-cli/src/test/resources/ballerina-to-openapi/response/status_code_errors_03.bal
> $Subject
Fixes:
- https://github.com/ballerina-platform/ballerina-library/issues/5135
Refer to the above issue for proposal and examples
> Add OAS mapping for HTTP status code errors

- openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java
- openapi-cli/src/test/resources/complexPath.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
> https://github.com/ballerina-platform/ballerina-library/issues/4850
Solution:
- It has been concluded during our discussion regarding the specification that remote functions should be generated for the OpenAPI contract that includes handling complex URLs such as parameterized sub-segments, as discussed here: https://github.com/ballerina-platform/ballerina-spec/issues/1238. within the tool, the fix will be to automatically fall in back to generate a remote function for the entire yaml by providing a warning message.
- For the service resource functions, we are not going to generate resource functions for the given contract. …
> [master] Fix for service and client generation when OAS include parameterized path segmentes in paths

- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/BallerinaClientGenerator.java
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6193
To this fix updating the lang timestamp is not required because the lang timestamp doesn't contain some changes in the https://github.com/ballerina-platform/ballerina-lang/pull/42251.
> [master] Fix for openAPI client generation test failures

- build.gradle
- gradle.properties
- openapi-bal-task-plugin/src/main/java/io/ballerina/openapi/bal/tool/OpenAPICodeGeneratorTool.java
- openapi-build-extension/src/main/java/io/ballerina/openapi/build/HttpServiceAnalysisTask.java
- openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java
- openapi-client-native/build.gradle
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/GeneratorUtils.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/diagnostic/CommonDiagnosticMessages.java
> $Subject
- Add a property to skip publishing client native artifacts to WSO2 nexus. With this change, we have to enable this in the `gradle.properties` file, if we want to publish the artifacts with release workflow. If we do not need to release we need to mark it as `true`
- Fix optional response header mapping in the status code response. Without this change, when we have non-required headers in status code response, it is map to `map<string|string[]>`. With this change, the optional headers will be mapped as nilable record fields
- Fix printing `Responses with 204 status code cannot have a body` warning for response which does not define a request body schema
- Removed unused `OAS_COMMON_102` from the common diagnostics
- Print the client warning/error diagnostics when bal commands …
> Fix minor issues found in RC testing

- openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java
- openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java
- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RemoteFunctionNameValidationTests.java
- openapi-cli/src/test/resources/petstore_with_complex_path_and_without_operation_id.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/GeneratorUtils.java
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6711
> Fix NPE when operation ID is missing for operations with complex path

- .github/CODEOWNERS
- module-ballerina-openapi/Ballerina.toml
- module-ballerina-openapi/CompilerPlugin.toml
- openapi-cli/src/test/java/io/ballerina/openapi/generators/common/OASModifierTests.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/GeneratorUtils.java
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/OASModifier.java
>  $Subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6897
> Restructure the name modification function

- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/Constants.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/parameter/QueryParameterMapper.java
- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/utils/MapperCommonUtils.java
- docs/ballerina-to-oas/spec/spec.md
- gradle.properties
- openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/QueryParameterTests.java
- openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/query/query_scenario10.yaml
- openapi-cli/src/test/resources/ballerina-to-openapi/query/query_scenario10.bal
- openapi-integration-tests/src/test/resources/ballerina_sources/project_openapi_bal_ext/result_1.yaml
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6984
This PR maps the name from the `http:Query` annotation for the query parameter name in the generated OpenAPI specification. This new field is introduced via https://github.com/ballerina-platform/module-ballerina-http/pull/2143
> Add OpenAPI mapping support for query annotation with name field

- build.gradle
- gradle.properties
- module-ballerina-openapi/annotation.bal
- openapi-client-native/ballerina-tests/Dependencies.toml
- openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/BallerinaToOpenAPICLINegativeTests.java
- openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/BallerinaToOpenAPITests.java
- openapi-integration-tests/src/test/resources/ballerina_sources/project_openapi_info_with_service_contract_type/Ballerina.toml
- openapi-integration-tests/src/test/resources/ballerina_sources/project_openapi_info_with_service_contract_type/result.yaml
- openapi-integration-tests/src/test/resources/ballerina_sources/project_openapi_info_with_service_contract_type/service_file.bal
- openapi-integration-tests/src/test/resources/ballerina_sources/project_openapi_info_with_service_contract_type_and_declaration/Ballerina.toml
- openapi-integration-tests/src/test/resources/ballerina_sources/project_openapi_info_with_service_contract_type_and_declaration/result.yaml
- openapi-integration-tests/src/test/resources/ballerina_sources/project_openapi_info_with_service_contract_type_and_declaration/service_file.bal
> Fix https://github.com/ballerina-platform/ballerina-library/issues/7334
- Unit tests 
- Integration tests - add
> Describe the research phase and any blog …
> [master]Fix the `openapi:ServiceInfo` annotation is not supported in the service contract type 

- openapi-cli/src/test/java/io/ballerina/openapi/generators/client/UtilGenerationTests.java
- openapi-cli/src/test/resources/generators/client/ballerina/multipart_formdata_array_client.bal
- openapi-cli/src/test/resources/generators/client/ballerina/multipart_formdata_array_utils.bal
- openapi-cli/src/test/resources/generators/client/utils/swagger/multipart_formdata_array.yaml
- openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/BallerinaUtilGenerator.java
- openapi-core/src/main/resources/templates/utils_openapi.bal
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6872
> Fix util issue with multipart/formdata

- gradle.properties
- openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ResponseTests.java
- testResponseWithReadOnlySimpleNameReferenceReturnType
- testNilUnionReturnType
These tests were disabled due to the failure in the PR in the Ballerina Lang repo. 
These will be enable once the this issue resolved: https://github.com/ballerina-platform/ballerina-library/issues/7452
> [master] Disable openAPI tests

- openapi-cli/src/main/java/io/ballerina/openapi/cmd/Flatten.java
- openapi-cli/src/main/java/io/ballerina/openapi/cmd/Sanitize.java
- openapi-cli/src/main/java/io/ballerina/openapi/cmd/SubCmdBase.java
- openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java
- openapi-cli/src/test/resources/cmd/sanitize/openapi_unresolved.yaml
- openapi-cli/src/test/resources/cmd/sanitize/sanitized_openapi_unresolved_expected.yaml
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7464
> Enable resolver for sanitize sub command

- ballerina-to-openapi/build.gradle
- build.gradle
- gradle.properties
In some scenarios where we do not do any changes to the `ballerina-to-openapi` package, we need skip release this particular package
> Add an option to disable ballerinaToOpenAPI publish

- ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/type/extension/BallerinaTypeExtensioner.java
Unsupported types(like singletons which are not yet supported) will have a null schema which is causing this issue
> $Subject
> [2201.12.x] Fix NPE in the extension generator due to unsupported type schemas
