.github/workflows/publish-release.yml, gradle.properties
=> Update GitHub workflow for publish 

openapi-cli/build.gradle, openapi-cli/src/main/java/module-info.java, openapi-cli/src/main/java/org/ballerinalang/ballerina/openapi/convertor/service/OpenApiConverterUtils.java, openapi-validator/build.gradle, openapi-validator/src/main/java/module-info.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/Filters.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenAPIValidatorPlugin.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenApiValidatorUtil.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceMethod.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourcePathSummary.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceWithOperationId.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/error/OpenapiServiceValidationError.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/error/ResourceValidationError.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/error/ValidationError.java, openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/OpenApiFilterTests.java, openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ServiceValidationTests.java
=> Update openAPI Diagnostic usage with new Diagnostic API

openapi-cli/build.gradle, openapi-cli/src/main/java/module-info.java, openapi-cli/src/main/java/org/ballerinalang/ballerina/openapi/convertor/service/OpenApiConverterUtils.java, openapi-validator/build.gradle, openapi-validator/src/main/java/module-info.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/Filters.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenAPIValidatorPlugin.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenApiValidatorUtil.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceMethod.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourcePathSummary.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceWithOperationId.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ServiceValidator.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/error/OpenapiServiceValidationError.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/error/ResourceValidationError.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/error/ValidationError.java, openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/OpenApiFilterTests.java, openapi-validator/src/test/java/org/ballerinalang/openapi/validator/tests/ServiceValidationTests.java
=> Update diagnostic log usage with new diagnostic API

gradle.properties
=> Update  gradle.properties file

module-ballerina-openapi/build.gradle
=> Fix issue with OpenAPI distribution pack 

build.gradle, module-ballerina-openapi/build.gradle, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/Constants.java, openapi-validator/src/main/java/org/ballerinalang/openapi/validator/OpenAPIValidatorPlugin.java
=> Fix brokens in openapi-validator with projectAPI and diagnosticLog chagnes 

.github/workflows/publish-release.yml
=> Fix OpenAPI publish workflow

gradle.properties
=> Update openAPI version

gradle.properties, openapi-validator/src/main/java/module-info.java
=> Update version in gradle.properties

openapi-cli/src/main/java/org/ballerinalang/openapi/CodeGenerator.java, openapi-cli/src/main/java/org/ballerinalang/openapi/utils/GeneratorConstants.java, openapi-cli/src/main/resources/templates/client/client-ep.mustache, openapi-cli/src/main/resources/templates/service/balService.mustache, openapi-cli/src/test/resources/expected_gen/generateClient.bal
=> Fix issue with openAPI generated file name

openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java
=> Fix NPE issue with output path

openapi-cli/src/main/java/org/ballerinalang/openapi/OpenApiMesseges.java, openapi-cli/src/test/java/org/ballerinalang/openapi/CodeGeneratorTest.java, openapi-cli/src/test/resources/expected_gen/generateSkeleton.bal
=> Update openapi keyword list with ballerina keywords

openapi-cli/src/main/java/org/ballerinalang/ballerina/OpenApiConverterUtils.java
=> Fix issue with input path in ballerina-to-openAPI cmd

openapi-cli/src/main/java/org/ballerinalang/ballerina/OpenApiConverterUtils.java, openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java, openapi-cli/src/test/resources/ballerina-to-openapi/no_base_path_service.bal
> $subject. Fixes https://github.com/ballerina-platform/ballerina-openapi/issues/50.
=> Fix ballerina to OpenAPI with no base path in Ballerina Service

openapi-cli/src/main/resources/templates/client/client-ep.mustache, openapi-cli/src/test/java/org/ballerinalang/openapi/CodeGeneratorTest.java, openapi-cli/src/test/resources/expected_gen/generateClient.bal, openapi-cli/src/test/resources/expected_gen/generate_client_requestbody.bal, openapi-cli/src/test/resources/openapi-client-rb.yaml
=> Fix client generation with new service changes

openapi-cli/src/main/java/org/ballerinalang/ballerina/service/OpenApiResourceMapper.java
=> Fix align openAPI-CLI implementation with new fieldSymbol changes

openapi-cli/src/main/java/org/ballerinalang/openapi/utils/TypeExtractorUtil.java, openapi-cli/src/main/resources/templates/service/balService.mustache, openapi-cli/src/test/java/org/ballerinalang/openapi/CodeGeneratorTest.java, openapi-cli/src/test/resources/expected_gen/generateSkeleton.bal, openapi-cli/src/test/resources/expected_gen/generatedRB.bal
> $Subject
Add review suggestions in this  (PR https://github.com/ballerina-platform/ballerina-distribution/pull/1190) 
> Link to …
=> Fix openapi service resource functions' documention suggestions

build.gradle, gradle.properties, openapi-tests/build.gradle
=> Remove config module dependency 

gradle.properties
=> Update ballerina lang version in gradle.properties file

openapi-cli/src/main/resources/templates/client/client-ep.mustache, openapi-cli/src/test/java/org/ballerinalang/openapi/CodeGeneratorTest.java, openapi-cli/src/test/resources/expected_gen/generate_client.bal, openapi-cli/src/test/resources/expected_gen/generate_client_requestbody.bal
=> Update OpenAPI client generation template

gradle.properties
=> Update ballerina lang and stdlib versions

module-ballerina-openapi/build.gradle
=> Replace balo with bala

module-ballerina-openapi/Ballerina.toml, module-ballerina-openapi/build.gradle
=> Fix issue with daily build workflow

openapi-cli/src/main/java/org/ballerinalang/ballerina/service/OpenApiResourceMapper.java
=> Replace symbol 'name()' method to 'getName()'

.github/workflows/build-master.yml, .github/workflows/codecov.yaml, .github/workflows/pull-request.yml, README.md, build.gradle, gradle.properties, gradle/javaProject.gradle, module-ballerina-openapi/build.gradle, openapi-cli/build.gradle, openapi-cli/src/test/resources/ballerina-to-openapi/project_bal/Package.md, openapi-validator/build.gradle
=> Fix add Codecov Report Publishing

.github/workflows/build-master.yml
=> Fix master build workflow issue

openapi-cli/src/main/java/org/ballerinalang/ballerina/OpenApiConverterUtils.java, openapi-cli/src/main/java/org/ballerinalang/ballerina/service/OpenApiResourceMapper.java, openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/path_scenario01.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/path_scenario02.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/path_scenario03.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/path_scenario01.bal, openapi-cli/src/test/resources/ballerina-to-openapi/path_scenario02.bal, openapi-cli/src/test/resources/ballerina-to-openapi/path_scenario03.bal
=> Fix OpenAPI spec should have `/` for the path when the service path is `.` 

openapi-cli/src/main/java/org/ballerinalang/generators/GeneratorUtils.java, openapi-cli/src/test/resources/expected_gen/generateSkeleton.bal, openapi-cli/src/test/resources/expected_gen/generated_bal.bal, openapi-cli/src/test/resources/expected_gen/petstoreOperation.bal, openapi-cli/src/test/resources/generators/ballerina/multi_paths.bal, openapi-cli/src/test/resources/generators/ballerina/path_parameters.bal, openapi-cli/src/test/resources/generators/swagger/multiPaths.yaml
=> Remove prefix '/' from relative path in resource functions

openapi-cli/src/main/java/org/ballerinalang/ballerina/service/OpenApiResourceMapper.java, openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaServiceGenerator.java, openapi-cli/src/main/java/org/ballerinalang/generators/GeneratorUtils.java, openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java, openapi-cli/src/test/java/org/ballerinalang/generators/BallerinaServiceGeneratorTest.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/rs_scenario10.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/rs_scenario10.bal, openapi-cli/src/test/resources/expected_gen/generatedRB.bal, openapi-cli/src/test/resources/expected_gen/multi_query_para.bal, openapi-cli/src/test/resources/generators/ballerina/listeners.bal, openapi-cli/src/test/resources/generators/ballerina/listeners03.bal, openapi-cli/src/test/resources/generators/ballerina/path_parameters02.bal, openapi-cli/src/test/resources/generators/swagger/multiPathParam02.yaml, openapi-cli/src/test/resources/generators/swagger/petstore_listeners02.yaml, openapi-cli/src/test/resources/generators/swagger/petstore_listeners03.yaml, openapi-cli/src/test/resources/requestBody.yaml
> This PR for handling the array type of the response payload in `ballerina to openapi` command
sample ballerina resource function
```ballerina
resource function post hi01(http:Caller caller, http:Request request) returns Pet[] {
}
resource function post hi(http:Caller caller, http:Request request) returns string[] {}
```
out put generated yaml file
```
paths:
/hi01:
post:
operationId: operation1_post_/hi01
responses:
"200":
description: Ok
content:
schema:
type: array
items:
$ref: '#/components/schemas/Pet'
/hi:
post:
operationId: operation1_post_/hi
responses:
"200":
description: Ok
content:
text/plain:
schema:
type: array
items:
type: string
```
> Improve the path parameter in `openapi to ballerina` when having path as a path parameter
Input openapi file 
```
path: …
```
=> Added improvements for handling the array type in Response payload

openapi-cli/src/main/java/org/ballerinalang/generators/GeneratorUtils.java, openapi-cli/src/test/resources/generators/ballerina/path_parameters.bal, openapi-cli/src/test/resources/generators/swagger/multiPathParam.yaml
=> Fix issue with path parameter type in openapi to ballerina command

build.gradle, gradle.properties, openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java, openapi-cli/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java, openapi-cli/src/test/resources/ballerina-to-openapi/basic_service.bal, openapi-cli/src/test/resources/ballerina-to-openapi/complex_base_path.bal, openapi-cli/src/test/resources/ballerina-to-openapi/json_payload_service.bal, openapi-cli/src/test/resources/ballerina-to-openapi/mime_with_recordpayload_service.bal, openapi-cli/src/test/resources/ballerina-to-openapi/multiple_payload_service.bal, openapi-cli/src/test/resources/ballerina-to-openapi/path_scenario01.bal, openapi-cli/src/test/resources/ballerina-to-openapi/rs_scenario10.bal, openapi-cli/src/test/resources/ballerina-to-openapi/xml_payload_service.bal, openapi-cli/src/test/resources/testng.xml
=> Update Time and Task module versions

.github/workflows/daily-build.yml, .github/workflows/pull-request.yml, openapi-cli/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java, openapi-cli/src/test/resources/testng.xml
=> Fixed Windows tests failure 

openapi-cli/src/main/java/org/ballerinalang/ballerina/service/OpenApiResourceMapper.java, openapi-cli/src/main/resources/templates/client/client-ep.mustache, openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/rb_scenario11.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/rb_scenario11.bal, openapi-cli/src/test/resources/expected_gen/generate_client.bal, openapi-cli/src/test/resources/expected_gen/generate_client_requestbody.bal
=> Fix for handling multiple records in ballerina to openapi command

gradle.properties, openapi-cli/src/main/java/org/ballerinalang/ballerina/OpenApiConverterUtils.java, openapi-cli/src/main/java/org/ballerinalang/ballerina/service/ConverterConstants.java, openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaSchemaGenerator.java, openapi-cli/src/main/java/org/ballerinalang/generators/ErrorMessages.java, openapi-cli/src/main/java/org/ballerinalang/generators/GeneratorUtils.java, openapi-cli/src/main/java/org/ballerinalang/openapi/CodeGenerator.java, openapi-cli/src/main/java/org/ballerinalang/openapi/OpenApiMesseges.java, openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java, openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java, openapi-cli/src/test/java/org/ballerinalang/openapi/CodeGeneratorTest.java, openapi-cli/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java
Fix for improving error messages, the behaviour of the file regenerate prompt,  and formatting issues with generated schema file.
Update the dependency versions.
> Fix 
#137
#138 
#139
#151
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Improve generated file name in both OpenAPI commands

openapi-validator/src/main/java/org/ballerinalang/openapi/validator/ResourceValidator.java
=> Fix align path parameter symbol with new semantic API changes

README.md
=> Fix a Broken Link and Correct Grammar Issues in README.md

openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaSchemaGenerator.java, openapi-cli/src/main/java/org/ballerinalang/openapi/OpenApiMesseges.java, openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java, openapi-cli/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICmdTest.java, openapi-cli/src/test/java/org/ballerinalang/openapi/cmd/OpenAPICommandTest.java, openapi-cli/src/test/resources/petstore.yml
=> Fix add exit code for openAPI command

.github/workflows/build-timestamped-master.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml
=> Add timestamped version publishing configs

build.gradle, module-ballerina-openapi/build.gradle
=> Strip timestamped version when building ballerina-openapi

openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaSchemaGenerator.java, openapi-cli/src/test/resources/expected_gen/petstore_schema.bal, openapi-cli/src/test/resources/generators/ballerina/schema/schema01.bal, openapi-cli/src/test/resources/generators/ballerina/schema/schema02.bal, openapi-cli/src/test/resources/generators/ballerina/schema/schema03.bal, openapi-cli/src/test/resources/generators/ballerina/schema/schema04.bal, openapi-cli/src/test/resources/generators/ballerina/schema/schema05.bal, openapi-cli/src/test/resources/generators/ballerina/schema/schema06.bal, openapi-cli/src/test/resources/generators/ballerina/schema/schema07.bal, openapi-cli/src/test/resources/generators/ballerina/schema/schema08.bal, openapi-cli/src/test/resources/generators/ballerina/schema/schema09.bal, openapi-cli/src/test/resources/generators/ballerina/schema/schema10.bal, openapi-cli/src/test/resources/generators/ballerina/schema/schema11.bal
=> Make OpenAPI schema record type as public

openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java
=> Disable the ballerina to OpenAPI array type response handle test

openapi-cli/src/main/java/org/ballerinalang/openapi/cmd/OpenApiCmd.java
=> Fix issue with OpenAPI CLI command

openapi-cli/src/main/java/org/ballerinalang/ballerina/OpenApiConverterUtils.java, openapi-cli/src/main/java/org/ballerinalang/generators/BallerinaServiceGenerator.java, openapi-cli/src/test/java/org/ballerinalang/ballerina/OpenApiConverterUtilsTest.java, openapi-cli/src/test/java/org/ballerinalang/generators/BallerinaServiceGeneratorTest.java, openapi-cli/src/test/resources/expected_gen/generateSkeleton.bal, openapi-cli/src/test/resources/expected_gen/generated_bal.bal, openapi-cli/src/test/resources/expected_gen/multi_query_para.bal, openapi-cli/src/test/resources/expected_gen/petstoreOperation.bal, openapi-cli/src/test/resources/expected_gen/petstoreTag.bal, openapi-cli/src/test/resources/generators/ballerina/header_parameters.bal, openapi-cli/src/test/resources/generators/ballerina/importors.bal, openapi-cli/src/test/resources/generators/ballerina/listeners.bal, openapi-cli/src/test/resources/generators/ballerina/listeners03.bal, openapi-cli/src/test/resources/generators/ballerina/multi_operations.bal, openapi-cli/src/test/resources/generators/ballerina/path_parameters.bal, openapi-cli/src/test/resources/generators/ballerina/petstore_default.bal, openapi-cli/src/test/resources/generators/ballerina/query_parameters.bal, openapi-cli/src/test/resources/generators/ballerina/service_gen.bal, openapi-cli/src/test/resources/generators/swagger/petstore_default.yaml
=> Fix default response type in ballerina service generation 

openapi-validator/build.gradle
> Remove gson dependency packing from OpenAPI validator build.gradle file due to this warning 
```Generating executable
warning: Detected conflicting jar files:
'openapi-validator-0.9.0-beta.1-20210506-051500-ec15322.jar' dependency of 'ballerina/openapi' conflict with 'ballerina-rt-2.0.0-beta.1-20210506-022400-d44e7336.jar' dependency of 'hansani/validatorTest'
target/bin/validatorTest.jar
```
> Summary of user stories …
=> Remove gson dependency from OpenAPI validator build.gradle file

openapi-cli/src/main/java/io/ballerina/generators/GeneratorConstants.java, openapi-cli/src/main/java/io/ballerina/openapi/CodeGenerator.java, openapi-cli/src/test/java/io/ballerina/generators/BallerinaClientGeneratorTests.java, openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java, openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java
> Fix #225 
Fix [https://github.com/wso2-enterprise/choreo/issues/4033](https://github.com/wso2-enterprise/choreo/issues/4033)
> …
=> Fix Change schema.bal name to types.bal and client name to client.bal

openapi-cli/src/main/java/io/ballerina/generators/BallerinaClientGenerator.java, openapi-cli/src/test/java/io/ballerina/generators/BallerinaClientGeneratorTests.java, openapi-cli/src/test/resources/generators/client/ballerina/multiple_pathparam.bal, openapi-cli/src/test/resources/generators/client/ballerina/openapi_weather_api.bal, openapi-cli/src/test/resources/generators/client/swagger/multiple_pathparam.yaml
> Fix #231 
Fix [https://github.com/wso2-enterprise/choreo/issues/4010](https://github.com/wso2-enterprise/choreo/issues/4010)
> …
=> Fix syntax Issue with the generated path parameter in OpenAPI Client

module-ballerina-openapi/Package.md
=> Fix incorrect module description

module-ballerina-openapi/Module.md, module-ballerina-openapi/Package.md, module-ballerina-openapi/annotation.bal
=> Fix documentation issue

module-ballerina-openapi/Module.md
=> Fix Module.md file

openapi-cli/src/test/java/io/ballerina/generators/auth/ApiKeyAuthTests.java, openapi-cli/src/test/java/io/ballerina/generators/auth/HttpAuthTests.java, openapi-cli/src/test/java/io/ballerina/generators/auth/OAuth2Tests.java
=> Fix incorrect test method name

build.gradle
=> Fix version branch for release

openapi-cli/src/main/java/io/ballerina/generators/BallerinaClientGenerator.java, openapi-cli/src/main/java/io/ballerina/generators/BallerinaSchemaGenerator.java, openapi-cli/src/main/java/io/ballerina/generators/BallerinaServiceGenerator.java, openapi-cli/src/main/java/io/ballerina/generators/GeneratorUtils.java, openapi-cli/src/test/java/io/ballerina/generators/common/SwaggerParserTests.java, openapi-cli/src/test/java/io/ballerina/generators/schema/BallerinaSchemaGeneratorTests.java, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/covid19_openapi.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/jira_openapi.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/uber_openapi.bal, openapi-cli/src/test/resources/generators/client/swagger/invalid.yaml, openapi-cli/src/test/resources/generators/schema/ballerina/openapi_weather_api_schema.bal, openapi-cli/src/test/resources/generators/schema/swagger/invalid.yaml, openapi-cli/src/test/resources/testng.xml
=> Fix anydata type handling

openapi-cli/src/main/java/io/ballerina/generators/BallerinaSchemaGenerator.java, openapi-cli/src/test/java/io/ballerina/generators/client/BallerinaClientGeneratorTests.java, openapi-cli/src/test/java/io/ballerina/generators/schema/BallerinaSchemaGeneratorTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/openapi.bal, openapi-cli/src/test/resources/generators/schema/swagger/openapi.yaml
=> Fix issue with openAPI schema has property field oneOf , anyOf , allOf type

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, build.gradle
> fix issue [https://github.com/ballerina-platform/ballerina-release/issues/547](https://github.com/ballerina-platform/ballerina-release/issues/547)
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
=> Improve GitHub Action Scripts 

openapi-cli/src/main/java/io/ballerina/generators/BallerinaClientGenerator.java, openapi-cli/src/main/java/io/ballerina/generators/BallerinaSchemaGenerator.java, openapi-cli/src/main/java/io/ballerina/generators/GeneratorUtils.java, openapi-cli/src/main/java/io/ballerina/openapi/CodeGenerator.java, openapi-cli/src/test/java/io/ballerina/generators/client/FunctionBodyNodeTests.java, openapi-cli/src/test/java/io/ballerina/generators/common/TestUtils.java, openapi-cli/src/test/java/io/ballerina/generators/schema/AdvanceRecordTypeTests.java, openapi-cli/src/test/java/io/ballerina/generators/schema/AllOfDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/generators/schema/AnyOfDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/generators/schema/ArrayDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/generators/schema/NullableFieldTests.java, openapi-cli/src/test/java/io/ballerina/generators/schema/OneOfDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/generators/schema/PrimitiveDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/generators/schema/RecordDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/generators/schema/ReferenceResolveTests.java, openapi-cli/src/test/java/io/ballerina/generators/schema/SwaggerFileParserTests.java, openapi-cli/src/test/resources/generators/client/swagger/put_with_header.yaml, openapi-cli/src/test/resources/generators/schema/ballerina/nullable_array.bal, openapi-cli/src/test/resources/generators/schema/ballerina/nullable_primitive.bal, openapi-cli/src/test/resources/generators/schema/ballerina/nullable_record.bal, openapi-cli/src/test/resources/generators/schema/ballerina/object_without_fields_reference.bal, openapi-cli/src/test/resources/generators/schema/ballerina/world_bank.bal, openapi-cli/src/test/resources/generators/schema/swagger/nullable_array_schema.yaml, openapi-cli/src/test/resources/generators/schema/swagger/nullable_primitive_schema.yaml, openapi-cli/src/test/resources/generators/schema/swagger/nullable_record_schema.yaml, openapi-cli/src/test/resources/generators/schema/swagger/nullable_schema.yaml, openapi-cli/src/test/resources/generators/schema/swagger/object_without_fields_reference.yaml, openapi-cli/src/test/resources/generators/schema/swagger/world_bank.yaml, openapi-cli/src/test/resources/testng.xml
> Fix [https://github.com/wso2-enterprise/choreo/issues/5141](https://github.com/wso2-enterprise/choreo/issues/5141)
Fix [https://github.com/wso2-enterprise/choreo/issues/5098](https://github.com/wso2-enterprise/choreo/issues/5098)
> This supports swagger schema enables nullable for an object, array, primitive data types.
```openapi
components:
schemas:
UserPlayListDetails:
externalDocs:
description: Find more info on the official Spotify Web API Reference
url: https://developer.spotify.com/documentation/web-api/reference/#object-pagingobject
properties:
href:
description: A link to the Web API endpoint returning the full result of the request
type: string
items:
description: The requested data.
items:
$ref: "#/components/schemas/ListObject"
nullable: true
limit:
description: The maximum …
```
=> Fix Handle nullable record field in openAPI schema generation

openapi-cli/src/main/java/io/ballerina/generators/BallerinaSchemaGenerator.java, openapi-cli/src/test/java/io/ballerina/generators/schema/ArrayDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/generators/schema/PrimitiveDataTypeTests.java, openapi-cli/src/test/resources/expected_gen/petstore_schema.bal, openapi-cli/src/test/resources/generators/schema/ballerina/schema08.bal, openapi-cli/src/test/resources/generators/schema/ballerina/schema_with_array.bal, openapi-cli/src/test/resources/generators/schema/ballerina/schema_with_nested_array.bal, openapi-cli/src/test/resources/generators/schema/ballerina/schema_with_primitive.bal, openapi-cli/src/test/resources/generators/schema/swagger/schema_with_array.yaml, openapi-cli/src/test/resources/generators/schema/swagger/schema_with_nested_array.yaml, openapi-cli/src/test/resources/generators/schema/swagger/schema_with_primitive.yaml, openapi-cli/src/test/resources/testng.xml
> Fix #296 
Fix [https://github.com/wso2-enterprise/choreo/issues/5225](https://github.com/wso2-enterprise/choreo/issues/5225)
Address this type of schema scenarios 
```
components:
schemas:
PetNames:
items:
type: string
Address:
properties:
streetNo:
type: integer
mainStreet:
type: string
country:
type: string
UserAddress:
items:
$ref: '#/components/schemas/Address'
```
Generated ballerina types
```ballerina
public type PetNames string[];
public type Address record {
int streetNo?;
string mainStreet?;
string country?;
};
public type UserAddress Address[];
```
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email …
=> Fix Handle schema generation for array, primitive data type under the component schema 

openapi-cli/src/main/java/io/ballerina/generators/BallerinaClientGenerator.java, openapi-cli/src/main/java/io/ballerina/generators/BallerinaSchemaGenerator.java, openapi-cli/src/main/java/io/ballerina/generators/GeneratorUtils.java, openapi-cli/src/test/resources/expected_gen/generate_client.bal, openapi-cli/src/test/resources/expected_gen/generate_client_requestbody.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/openapi_weather_api.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/uber_openapi.bal, openapi-cli/src/test/resources/generators/client/file_provider/swagger/openapi.yaml
=> Fix Handle remote function request body when it has inline record

openapi-cli/src/main/java/io/ballerina/openapi/utils/CodegenUtils.java, openapi-cli/src/test/resources/expected_gen/allOf-schema-petstore.bal, openapi-cli/src/test/resources/expected_gen/generateSkeleton.bal, openapi-cli/src/test/resources/expected_gen/generate_client.bal, openapi-cli/src/test/resources/expected_gen/generate_client_requestbody.bal, openapi-cli/src/test/resources/expected_gen/generatedRB.bal, openapi-cli/src/test/resources/expected_gen/generated_bal.bal, openapi-cli/src/test/resources/expected_gen/inline-request-expected.bal, openapi-cli/src/test/resources/expected_gen/multi_query_para.bal, openapi-cli/src/test/resources/expected_gen/oneof-schema-petstore.bal, openapi-cli/src/test/resources/expected_gen/petstoreOperation.bal, openapi-cli/src/test/resources/expected_gen/petstoreTag.bal, openapi-cli/src/test/resources/expected_gen/petstore_gen.bal, openapi-cli/src/test/resources/expected_gen/petstore_schema.bal
=> Remove copyright header in generated file

openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java
=> Disable invalid test case

openapi-cli/src/main/java/io/ballerina/generators/BallerinaClientGenerator.java, openapi-cli/src/main/java/io/ballerina/generators/BallerinaSchemaGenerator.java, openapi-cli/src/main/java/io/ballerina/generators/GeneratorUtils.java, openapi-cli/src/test/java/io/ballerina/generators/client/ComparedGeneratedFileTests.java, openapi-cli/src/test/java/io/ballerina/generators/client/FunctionBodyNodeTests.java, openapi-cli/src/test/java/io/ballerina/generators/client/HeadersTests.java, openapi-cli/src/test/java/io/ballerina/generators/common/GeneratorUtilsTests.java, openapi-cli/src/test/resources/expected_gen/generate_client.bal, openapi-cli/src/test/resources/generators/client/ballerina/header_parameter.bal, openapi-cli/src/test/resources/generators/client/ballerina/query_param_with_default_value.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/openapi_weather_api.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/uber_openapi.bal, openapi-cli/src/test/resources/generators/client/file_provider/swagger/email_send.yaml, openapi-cli/src/test/resources/generators/client/file_provider/swagger/sendgrid.yaml
=> Fix header generation issue in beta.1 branch

openapi-cli/src/main/java/io/ballerina/generators/BallerinaClientGenerator.java, openapi-cli/src/test/java/io/ballerina/generators/client/ComparedGeneratedFileTests.java, openapi-cli/src/test/resources/expected_gen/generate_client.bal, openapi-cli/src/test/resources/generators/client/ballerina/client_template.bal, openapi-cli/src/test/resources/generators/client/ballerina/openapi_display_annotation.bal, openapi-cli/src/test/resources/generators/client/ballerina/operation_get.bal, openapi-cli/src/test/resources/generators/client/ballerina/query_param_with_default_value.bal, openapi-cli/src/test/resources/generators/client/ballerina/salesforce.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/jira_openapi.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/openapi_weather_api.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/uber_openapi.bal
=> Remove checkpainc from query parameter path generation function

openapi-cli/src/main/java/io/ballerina/generators/client/BallerinaTestGenerator.java
> $subject
> Generate `Config.toml` file along with the test cases
- Unit tests 
=> Fix issue Config.toml not generating

openapi-cli/src/main/java/io/ballerina/generators/client/FunctionSignatureGenerator.java, openapi-cli/src/test/java/io/ballerina/generators/client/QueryParameterTests.java, openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java, openapi-cli/src/test/resources/generators/client/swagger/invalid_query_param.yaml
=> Fix Client generation fails when the yaml has object type query parameters

openapi-cli/src/main/java/io/ballerina/generators/GeneratorUtils.java, openapi-cli/src/main/java/io/ballerina/generators/client/FunctionReturnType.java, openapi-cli/src/test/java/io/ballerina/generators/client/OneOfResponsesTests.java, openapi-cli/src/test/resources/generators/client/swagger/return_type/inline_oneOf_response.yaml, openapi-cli/src/test/resources/testng.xml
=> Fix response not generated properly when the response schema with oneOf has multiple items of type array

openapi-cli/src/main/java/io/ballerina/generators/BallerinaSchemaGenerator.java, openapi-cli/src/test/java/io/ballerina/generators/schema/NestedRecordInclusionTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/nested_schema_refs.bal, openapi-cli/src/test/resources/generators/schema/swagger/nested_schema_refs.yaml, openapi-cli/src/test/resources/testng.xml
> Fix https://github.com/ballerina-platform/ballerina-openapi/issues/368
> Java JDK 11
> Ballerina SL Beta2
=> Fix issue with schema referencing another schema

openapi-cli/src/main/java/io/ballerina/generators/client/BallerinaClientGenerator.java, openapi-cli/src/main/java/io/ballerina/generators/client/FunctionSignatureGenerator.java, openapi-cli/src/test/java/io/ballerina/generators/client/HeadersTests.java, openapi-cli/src/test/java/io/ballerina/generators/client/NoServerURLTest.java, openapi-cli/src/test/resources/generators/client/ballerina/header_param_with_default_value.bal, openapi-cli/src/test/resources/generators/client/ballerina/missing_server_url.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/openapi_weather_api.bal, openapi-cli/src/test/resources/generators/client/swagger/header_param_with_default_value.yaml, openapi-cli/src/test/resources/generators/client/swagger/missing_server_url.yaml, openapi-cli/src/test/resources/testng.xml
> Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/387
> Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/389
> Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/388
> Improving the usability of the generated code
- Unit tests 
> Java JDK 11
> Ballerina Swan Lake Beta2
=> [Bug Fix] Support headers with default values

openapi-cli/src/main/java/io/ballerina/openapi/cmd/CodeGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionSignatureGenerator.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/PathParameterTests.java, openapi-cli/src/test/resources/generators/client/ballerina/path_parameter_with_special_name.bal, openapi-cli/src/test/resources/generators/client/swagger/path_parameter_special_name.yaml
> $subject  
- This PR also includes fixes for below minor bugs. 
> Remove extra white space in import statements
> Let users to decide on overriding test files
Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/442
Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/423
> Resolves the bugs identified by the users. 
=> Format path parameter names

openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaClientGenerator.java, openapi-cli/src/test/resources/expected_gen/generate_client.bal, openapi-cli/src/test/resources/expected_gen/generate_client_requestbody.bal, openapi-cli/src/test/resources/expected_gen/generated_client_with_license.bal, openapi-cli/src/test/resources/expected_gen/x_init_description.bal, openapi-cli/src/test/resources/generators/client/ballerina/client_template.bal, openapi-cli/src/test/resources/generators/client/ballerina/header_param_with_default_value.bal, openapi-cli/src/test/resources/generators/client/ballerina/header_parameter.bal, openapi-cli/src/test/resources/generators/client/ballerina/header_without_parameter.bal, openapi-cli/src/test/resources/generators/client/ballerina/missing_server_url.bal, openapi-cli/src/test/resources/generators/client/ballerina/openapi_display_annotation.bal, openapi-cli/src/test/resources/generators/client/ballerina/operation_get.bal, openapi-cli/src/test/resources/generators/client/ballerina/operation_id.bal, openapi-cli/src/test/resources/generators/client/ballerina/operation_post.bal, openapi-cli/src/test/resources/generators/client/ballerina/path_param_with_ref_schema.bal, openapi-cli/src/test/resources/generators/client/ballerina/path_parameter_valid.bal, openapi-cli/src/test/resources/generators/client/ballerina/path_parameter_with_special_name.bal, openapi-cli/src/test/resources/generators/client/ballerina/query_param_with_default_value.bal, openapi-cli/src/test/resources/generators/client/ballerina/query_param_with_ref_schema.bal, openapi-cli/src/test/resources/generators/client/ballerina/query_param_without_default_value.bal, openapi-cli/src/test/resources/generators/client/ballerina/request_body_allOf_scenarios.bal, openapi-cli/src/test/resources/generators/client/ballerina/request_body_basic_scenarios.bal, openapi-cli/src/test/resources/generators/client/ballerina/request_body_oneOf_scenarios.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/covid19_openapi.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/multiple_pathparam.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/openapi_weather_api.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/operation.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/tag.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/uber_openapi.bal
> $subject
> Increase the usability of the connector. 
> Java JDK 11
=> Revamp connector init function doc comments 

openapi-cli/src/main/java/io/ballerina/openapi/cmd/CodeGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/common/GeneratorUtilsTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/common/SwaggerParserTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/SwaggerFileParserTests.java, openapi-cli/src/test/resources/invalid_petstore.yaml
> $subject
Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/492
> Increase the usability of the tool
> Java JDK 11
> Swagger parser https://github.com/swagger-api/swagger-parser
=> Provide detailed error message for invalid OpenAPI definition

openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/service/BallerinaServiceGenerator.java, openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/BallerinaServiceGeneratorTest.java, openapi-cli/src/test/resources/generators/ballerina/path_with_special_characters.bal, openapi-cli/src/test/resources/generators/swagger/path_with_special_characters.yaml
=> [Service] Fix issue with hyphens are not escaped for generated resource function names

.github/ISSUE_TEMPLATE/type_bug.md, .github/ISSUE_TEMPLATE/type_improvement.md, .github/ISSUE_TEMPLATE/type_new_feature.md, .github/ISSUE_TEMPLATE/type_task.md
> Fix #552 
>  Control the issue adding without proper `type/` to the repo. Increase the readability of the issue.
=> Fix add issue templates for ballerina OpenAPI repository

module-ballerina-openapi/Module.md, module-ballerina-openapi/Package.md
=> Fix issues in module.md and package.md files

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIEndpointMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ListenerTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/OpenApiConverterUtilsTest.java, openapi-cli/src/test/resources/ballerina-to-openapi/compiler_warning.bal, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/compiler_warning.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/listeners/with_check_key_word.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/listeners/listener_http_load_balancer.bal, openapi-extension-tests/src/test/java/io/ballerina/openapi/extension/OpenApiExtensionTest.java, openapi-extension-tests/src/test/resources/ballerina_sources/sample_7/service.bal
> Fix #558 
- Unit tests  - added
=> [BallerinaToOAS] Fix type cast issue in Ballerina to OpenAPI command

openapi-extension/src/main/java/io/ballerina/openapi/extension/OpenApiDocPackagingTask.java
=> [FIX] OpenAPI extension resource packaging logic

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ModuleReferenceTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/ballerina-project/service/Ballerina.toml, openapi-cli/src/test/resources/ballerina-to-openapi/ballerina-project/service/modules/mock/mock.bal, openapi-cli/src/test/resources/ballerina-to-openapi/ballerina-project/service/modules/representations/representations.bal, openapi-cli/src/test/resources/ballerina-to-openapi/ballerina-project/service/snowpeak.bal, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/snowpeak.yaml, openapi-cli/src/test/resources/testng.xml
=> [BallerinaToOAS]Fix for return type reference has separate ballerina module

openapi-cli/src/main/resources/templates/utils.bal, openapi-cli/src/test/resources/expected_gen/utils.bal
> $subject
> https://github.com/ballerina-platform/ballerina-openapi/pull/562
> Java JDK 11
=> Update utils.bal file template

openapi-cli/src/main/java/io/ballerina/openapi/generators/DocCommentsGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionSignatureGenerator.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/AnnotationTests.java, openapi-cli/src/test/resources/generators/client/swagger/deprecated_functions.yaml, openapi-cli/src/test/resources/generators/client/swagger/deprecated_parameter.yaml, openapi-cli/src/test/resources/generators/client/swagger/display_and_deprecated.yaml, openapi-cli/src/test/resources/generators/schema/swagger/deprecated_schemas.yaml
> Fix NPE in deprecated annotation generation …
=> Fix bug in deprecated annotation

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RecordTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/nullable01.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/nullable02.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/nullable03.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/record/nullable.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/nullable01.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/nullable02.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/nullable03.bal
> Fix #583 
- Unit tests  - add
> JDK 11
> https://swagger.io/docs/specification/data-models/data-types/#:~:text=considered%20boolean%20values.-,Null,-OpenAPI%203.0%20does
=> [BallerinaToOAS] Fix Nullable record field mapping to OAS schema properties

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RecordTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/TestUtils.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/nullable03.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/union.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/union_with_nullable.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/union_with_primitive.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/record/nullable01.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/nullable02.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/nullable03.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/optional.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/typeInclusion.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/union.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_nullable.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/union_with_primitive.bal
> Fix #587 
- Unit tests - add …
=> [BallerinaToOAS] fix for handling ballerina record field has Union type for OAS schema

openapi-validator/src/main/java/io/ballerina/openapi/validator/ServiceValidator.java, openapi-validator/src/test/java/io/ballerina/openapi/validator/tests/ServiceValidationTests.java
=> [Validator] Fix to NPE occurs when adding a new field to `openapi:ServiceInfo` annotation

openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ParameterGeneratorTest.java, openapi-cli/src/test/resources/generators/service/ballerina/service_gen_special_characters.bal, openapi-cli/src/test/resources/generators/service/swagger/petstore_service_with_special_characters.yaml
=> [Service]  Add test for hyphens escaped for generated resource function names

openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java
=> [Client] Remove extra spaces

openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ListenerGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceGenerationUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ListenerTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/RequestBodyTests.java, openapi-cli/src/test/resources/generators/service/ballerina/listeners/listeners05.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/refactor_record_name.bal, openapi-cli/src/test/resources/generators/service/ballerina/response/scenario_08_rs.bal, openapi-cli/src/test/resources/generators/service/ballerina/response/scenario_11_rs.bal, openapi-cli/src/test/resources/generators/service/swagger/listeners/petstore_listeners05.yaml, openapi-cli/src/test/resources/generators/service/swagger/requestBody/record_name_refactor.yaml
> Fix #632 
- Unit tests  -- added …
=> [Service] Fix issue with record name and service base path in generated service ballerina file

openapi-extension/src/main/java/io/ballerina/openapi/extension/doc/gen/AbstractOpenApiDocGenerator.java
>$subject
Related to [#2017](https://github.com/ballerina-platform/ballerina-standard-library/issues/2017)
=> Disable exception handling for OpenAPI in-built compiler plugin

openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java, openapi-cli/src/test/resources/expected_gen/generatedRB.bal, openapi-cli/src/test/resources/generators/service/ballerina/listeners/listeners05.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/refactor_record_name.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_0102_rb.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_01_rb.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_03_rb.bal
> Fix #654 
- Unit tests 
> Java 11, Ubuntu 20.04 …
=> [Service] Remove unnecessary curly brace from `@http:Payload` annotation

README.md
=> Update OpenAPI repository `README.md`

openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionSignatureGenerator.java
> Resolves https://github.com/ballerina-platform/ballerina-openapi/issues/685
=> [Client] Move escapeIdentifier() check inside the getValidName() function

openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIConverterService.java
=> [OpenAPILSExtension] Improve openapi lang server extension with new LS changes 

openapi-ls-extension/build.gradle, openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIConverterResponse.java, openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIConverterService.java, openapi-ls-extension/src/main/java/module-info.java
> Language server doesn't support List data type in remote data communication. LS extension was previously threw an exception because of this. 
From this PR, the YAML content's data type in the response of LS extension is refactored into a JSON array.
=> Update LS extension response type

openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaAuthConfigGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaClientGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/client/BallerinaTestGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/auth/MixedApiKeyAndHTTPAuthTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/auth/OAuth2Tests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/QueryParameterTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestConstants.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/testcases/BallerinaTestGeneratorTests.java, openapi-cli/src/test/resources/generators/client/ballerina/combination_of_apikey_and_http_oauth.bal, openapi-cli/src/test/resources/generators/client/swagger/combination_of_apikey_and_http_oauth.yaml, openapi-cli/src/test/resources/generators/test_cases/sample_yamls/combination_of_apikey_and_http_oauth.yaml, openapi-cli/src/test/resources/testng.xml
- Fix https://github.com/ballerina-platform/ballerina-openapi/issues/464
=> Support combination of apikey and httpOrOAuth authentication

openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorConstants.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/TypeGeneratorUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/OneOfDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/RecordDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/ReferenceResolveTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/empty_record.bal, openapi-cli/src/test/resources/generators/schema/ballerina/resolve_reference_docs.bal, openapi-cli/src/test/resources/generators/schema/swagger/empty_record.yaml, openapi-cli/src/test/resources/generators/schema/swagger/resolve_reference_docs.yaml
> $subject
> https://github.com/ballerina-platform/openapi-tools/pull/743
=> Bug fix in schema revamping

.github/workflows/build-timestamped-master.yml
=> Remove clean phase in publish GitHub task flow for avoiding twice building

.github/workflows/build-timestamped-master.yml, .github/workflows/pull-request.yml
=> Combine gradle tasks

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/CodegenUtils.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java, openapi-build-extension/src/main/java/io/ballerina/openapi/build/HttpServiceAnalysisTask.java, openapi-build-extension/src/main/java/io/ballerina/openapi/build/PluginConstants.java
=> Fix issue with generating duplicate OAS for build `--export-openapi` flag

openapi-build-extension/src/main/java/io/ballerina/openapi/build/HttpServiceAnalysisTask.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/BuildExtensionTests.java
> Generated YAML file has missed its extension …
=> Add `.yaml` extension to generated file in OpenAPI build plugin

openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java
> Resolves https://github.com/ballerina-platform/openapi-tools/issues/811
> Bug fix
=> [Client] Bug fix in API Keys 

gradle.properties, openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/ArrayTypeGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ParametersGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceGenerationUtils.java, openapi-extension-tests/build.gradle
=> Fix for syntax array API changes 

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIParameterMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/cmd/BallerinaToOASTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RequestBodyTest.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ResponseTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/rb_scenario13.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario19.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario20.yaml, openapi-cli/src/test/resources/cmd/ballerina-to-openapi/http_request.bal, openapi-cli/src/test/resources/cmd/ballerina-to-openapi/http_request.yaml, openapi-cli/src/test/resources/cmd/ballerina-to-openapi/http_response.bal, openapi-cli/src/test/resources/cmd/ballerina-to-openapi/http_response.yaml
>This PR is a patch for beta6.1 branch, related  main master PR https://github.com/ballerina-platform/openapi-tools/pull/838
> …
=> [BallerinaToOpenAPI] Add fix for `http:Request` and `http:Response` default accessor handling

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ModuleReferenceTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/ballerina-project/service/arrayTypeResponse.bal, openapi-cli/src/test/resources/ballerina-to-openapi/ballerina-project/service/modules/types/types.bal, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/arrayTypeResponse.yaml
> Fix #832 
- Unit tests - add
> Java JDK 11
=> [BallerinaToOpenAPI] Fix Invalid media type error is thrown when a resource method return type is a qualified name reference

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/diagnostic/DiagnosticMessages.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIParameterMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIRequestBodyMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResourceMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/cmd/BallerinaToOASTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RequestBodyTest.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ResponseTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/rb_scenario13.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/rb_scenario14.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario19.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario20.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/request_body/rb_scenario14.bal, openapi-cli/src/test/resources/cmd/ballerina-to-openapi/http_request.bal, openapi-cli/src/test/resources/cmd/ballerina-to-openapi/http_response.bal, openapi-cli/src/test/resources/cmd/ballerina-to-openapi/response.yaml
> Fix #836 
Fix #837 
Fix https://github.com/wso2-enterprise/choreo/issues/10414 …
=> [BallerinaToOpenAPI] Improve generating OpenAPI spec for `http:Request`, `http:Response` accessor

gradle.properties
=> Update ballerina lang version and openAPI tool version

gradle.properties
=> Update openAPI tool version to patch version

gradle.properties
=> Update ballerina lang version for beta6 patch release

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RecordTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/cyclic_record.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/record/cyclic_record.bal
=> [BallerinaToOpenAPI][Beta6] Fix cyclic record resolving issue

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/cyclic_record.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/record/cyclic_record.bal
> Avoid stack flower issue for record has
```ballerina
type ResponseError03 record {|
int? id;
ResponseError03[] resError?;
|};
```
FIx #wso2-enterprise/choreo#10791 …
=> [BallerinaToOpenAPI][beta6]Fix cyclic array record resolving issue

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/cyclic_record.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/record/cyclic_record.bal
=> [BallerinaToOAS][beta6] Fix issue with generated OAS for record field has array record with nullable

openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/ReferencedTypeGenerator.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/ReferenceResolveTests.java, openapi-cli/src/test/resources/generators/schema/swagger/undocument_ref.yaml
> Fix #873
- Unit tests  - added …
=> Fix issue with invalid OpenAPI definition that refers to an undefined schema

openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/cyclic_record.yaml
> $Subject
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.
> Link to drafts of marketing content that will describe and promote this feature, …
=> Fix Ballerina to OpenAPI test failure 

openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ReturnTypeGenerator.java, openapi-cli/src/test/resources/generators/service/ballerina/response/petstore_default.bal, openapi-cli/src/test/resources/generators/service/swagger/response/petstore_default.yaml
> Fix #880 
- Unit tests -added …
=> [Service] Fix `default` status code handle in response section for ballerina service generation

gradle.properties
=> Update OpenAPI version for GA release

openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ParameterGeneratorTest.java, openapi-cli/src/test/resources/generators/service/ballerina/path_parameters03.bal, openapi-cli/src/test/resources/generators/service/swagger/multiPathParam03.yaml
=> [Service] Fix issue with Path parameter is not generated for path name key 

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIEndpointMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIParameterMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIQueryParameterMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIRequestBodyMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResourceMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/OpenApiConverterUtilsTest.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/TestUtils.java, openapi-cli/src/test/resources/ballerina-to-openapi/escape_identifier.bal, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/escape_identifier.yaml
> Fix #894 
https://github.com/wso2-enterprise/choreo/issues/10976
=> [Beta6][BallerinaToOpenAPI] Fix for identifing escape characters when generating OpenAPI

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIEndpointMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIParameterMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIQueryParameterMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIRequestBodyMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResourceMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/OpenApiConverterUtilsTest.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/TestUtils.java, openapi-cli/src/test/resources/ballerina-to-openapi/escape_identifier.bal, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/escape_identifier.yaml
> Fix #894 
- Unit tests  - add
> [List any other related Issue](https://github.com/wso2-enterprise/choreo/issues/10976)
> Describe the research phase and any blog …
=> [BallerinaToOpenAPI] Fix for identifing escape characters when generating OpenApi

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIParameterMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/rb_scenario13.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario19.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario20.yaml, openapi-cli/src/test/resources/cmd/ballerina-to-openapi/response.yaml
> Fix #https://github.com/wso2-enterprise/choreo/issues/12053
- Unit tests 
> Describe the research phase and any blog posts, patterns, …
=> [BallerinaToOpenAPI] Add any type schema for default request and response in swagger

gradle.properties
=> Update OpenAPI and HTTP version

gradle.properties
=> Update Ballerina lang and HTTP version

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ResponseTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/no_body_field.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/response/without_body_field.bal
> Fix https://github.com/ballerina-platform/openapi-tools/issues/979 …
=> [BallerinaToOpenAPI]Fix for return record has no body field

gradle.properties
=> Update stable ballerina lang version

build.gradle, gradle.properties
> $Subject
Add GraphQL, gRPC and webhub dependency since those are used in integration test in openapi tool
=> update GraphQl, gRPC, websub version into stable version

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RecordTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/with_read_only_keyword.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/record/with_readonly_keyword.bal
=> Add fix for handle read-only in the record type

openapi-ls-extension/src/main/resources/META-INF/services/org.ballerinalang.langserver.commons.registration.BallerinaClientCapabilitySetter, openapi-ls-extension/src/main/resources/META-INF/services/org.ballerinalang.langserver.commons.registration.BallerinaServerCapabilitySetter
> Fix #https://github.com/ballerina-platform/openapi-tools/issues/1006 …
=> [1.1.x][OpenAPILS]Add LS extension `CapabilitySetter` into `resources/META-INF/services`

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/diagnostic/DiagnosticMessages.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIParameterMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIQueryParameterMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIRequestBodyMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResourceMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/DataTypeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/OpenApiConverterUtilsTest.java, openapi-cli/src/test/resources/ballerina-to-openapi/data_type/nullable_type_def.bal, openapi-cli/src/test/resources/ballerina-to-openapi/data_type/type_def.bal, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/nullable_type_def.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/type_def.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/escape_identifier.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/json/nestedRecord.json, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/nested_2record.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/nested_record.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/rb_scenario11.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/rb_scenario12.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/record_field_array.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/typeInclusion_01.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/snowpeak_request_body_ref.yaml, openapi-cli/src/test/resources/testng.xml
>  Fix https://github.com/wso2-enterprise/internal-support-ballerina/issues/98
- Unit tests 
> Describe the research phase and any blog …
=> Migrate Fix for issue [#1003] Service to OpenAPI description fails for type definitions types   to 2.0.5

gradle.properties
=> Update Ballerina lang version `2201.0.5-rc1`

gradle.properties
=> Update Ballerina lang stable version

gradle.properties
=> [1.1.x] Update Ballerina lang version

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/diagnostic/DiagnosticMessages.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIParameterMapper.java, openapi-build-extension/src/main/java/io/ballerina/openapi/build/HttpServiceAnalysisTask.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java, openapi-cli/src/test/java/io/ballerina/openapi/cmd/BallerinaToOASTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ListenerTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/QueryParameterTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RequestBodyTest.java, openapi-cli/src/test/resources/ballerina-to-openapi/data_type/type_def.bal, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/type_def.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/request_body/rb_scenario14.bal, openapi-cli/src/test/resources/ballerina-to-openapi/response/rs_scenario18.bal, openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/BallerinaToOpenAPITests.java, openapi-integration-tests/src/test/resources/ballerina_sources/project_2/hello_openapi.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_2/result.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_3/hello_openapi.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_3/result.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_4/hello_openapi.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_4/result.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_5/hello_openapi.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_5/result.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_8/hello_openapi.yaml, openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIConverterService.java, openapi-validator/src/main/java/io/ballerina/openapi/validator/PreValidator.java
> Fix #https://github.com/wso2-enterprise/internal-support-ballerina/issues/124
> Describe the research phase and any …
=> [BallerinaToOpenAPI] Fix issue with generating A request body defined under a GET resource 

openapi-cli/src/main/java/io/ballerina/openapi/cmd/CodeGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/client/FunctionBodyGenerator.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionBodyNodeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/HeadersTests.java, openapi-cli/src/test/resources/generators/client/ballerina/combination_of_apikey_and_http_oauth.bal, openapi-cli/src/test/resources/generators/client/ballerina/delete_with_header.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/api2pdf.bal, openapi-cli/src/test/resources/generators/client/swagger/delete_with_header.yaml
> Fix #1012 
#831 
https://github.com/wso2-enterprise/internal-support-ballerina/issues/113
- Unit tests 
> Code coverage information - add
> Describe the research …
=> [Client] Add support for DELETE method with header and request body

gradle.properties, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java, openapi-cli/src/test/resources/ballerina-to-openapi/data_type/enum.bal, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/enum.yaml
=> Fix enum value representation with new lang changes

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/MapTypeTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/data_type/map.bal, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/map.yaml, openapi-cli/src/test/resources/testng.xml
> Fix https://github.com/ballerina-platform/openapi-tools/issues/1013
- Unit tests -add
> Describe the research phase and any blog posts, …
=> [BallerinaToOpenAPI] Add support for map record field mapping 

openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ParametersGenerator.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/RequestBodyTests.java, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/reference_rb.bal, openapi-cli/src/test/resources/generators/service/swagger/requestBody/reference_rb.yaml
> Fix https://github.com/ballerina-platform/openapi-tools/issues/1037
- Unit tests 
> Describe the research phase and any blog posts, …
=> [1.1.x][Service]Add reference body support for service generation

openapi-cli/src/main/java/io/ballerina/openapi/generators/service/BallerinaServiceGenerator.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/RequestBodyTests.java, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/reference_rb.bal, openapi-cli/src/test/resources/generators/service/swagger/requestBody/reference_rb.yaml
=> [Master][Service]Add reference body support for service generation

openapi-validator/src/main/java/io/ballerina/openapi/validator/ReturnTypeValidator.java, openapi-validator/src/test/java/io/ballerina/openapi/validator/tests/ReturnTypeValidationTests.java, openapi-validator/src/test/resources/return/customized_mediaType.bal, openapi-validator/src/test/resources/return/customized_mediaType.yaml
>  $Subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus a brief explanation of why there’s no doc impact
> Type …
=> [Validator] Fix NPE that occur during media type validation

gradle.properties
=> Update Ballerina Lang version version

openapi-extension/build.gradle, openapi-extension/src/main/java/io/ballerina/openapi/extension/doc/gen/AbstractOpenApiDocGenerator.java, openapi-extension/src/main/java/module-info.java
> $subject
Fixes [#2419](https://github.com/ballerina-platform/ballerina-standard-library/issues/2419)
=> Remove the usage of Deprecated API in OpenAPI Built-in Plugin

openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/TypeGeneratorUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/ConstraintTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/record_field_02.bal, openapi-cli/src/test/resources/generators/schema/swagger/constraint/record_field_02.yaml
=> Fix for checking constraint value is non zero 

gradle.properties
=> Update ballerina lang version for 2201.1.2-rc1

openapi-cli/src/main/java/io/ballerina/openapi/cmd/OpenApiCmd.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/GeneratorUtils.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/BallerinaTypesGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/TypeGeneratorUtils.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/RecordTypeGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/UnionTypeGenerator.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/AnyOfDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/ConstraintTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/OneOfDataTypeTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/record_field_02.bal, openapi-cli/src/test/resources/generators/schema/ballerina/schema15.bal, openapi-cli/src/test/resources/generators/schema/swagger/constraint/record_field_02.yaml, openapi-cli/src/test/resources/generators/schema/swagger/constraint/union_type.yaml, openapi-cli/src/test/resources/generators/schema/swagger/scenario15.yaml, openapi-integration-tests/build.gradle, openapi-integration-tests/src/test/java/io/ballerina/openapi/OpenAPITest.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/SchemaGenerationTests.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/ServiceGeneratorReturnTypeTests.java, openapi-integration-tests/src/test/resources/schema/union.bal, openapi-integration-tests/src/test/resources/schema/union_type.yaml, openapi-integration-tests/src/test/resources/testng.xml
> Fix #1053  :  Missing type in Generated type.bal when anyOf has constraint scenarios
Fix #1054 :  Generate constraint gives compilation issue when the maxValue, minValue have decimal or float value
Fix #1056 :  Schema generation has compilation issue when the union type has constraint support
=> Fix constraint issues in connector generation

gradle.properties, openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/BallerinaTypesGenerator.java
=> Update Ballerina Lang Version

gradle.properties
=> [patch 2201.1.2-rc3] Update Ballerina lang version

gradle.properties
=> [patch 2201.1.2-rc3.1]Update ballerina version

gradle.properties
=> [Update 2201.2.0-rc3.2]Update dependency versions

gradle.properties
=> Update ballerina stable version `2201.2.0`

gradle.properties
=> [2201.1.2]Update stable ballerina lang version for patch

gradle.properties, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/OpenApiConverterUtilsTest.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/BallerinaClientGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/BallerinaTestGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/BallerinaUtilGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionBodyGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/BallerinaServiceGenerator.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/BuildExtensionTests.java, openapi-validator/src/test/java/io/ballerina/openapi/validator/tests/PreValidationTests.java
> $Subject
Disable some tests since they need to have some dependency latest version with new changes. 
> Link to the PR for …
=> Fix lang syntax API changes

README.md
> $Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3463
> Link to the PR for changes …
=> Replace slack channel with discord

openapi-client-idl-plugin/src/main/java/io/ballerina/openapi/idl/client/Constants.java, openapi-client-idl-plugin/src/main/java/io/ballerina/openapi/idl/client/OpenAPIClientGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/ErrorMessages.java, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/idl/client/IDLClientGenPluginNegativeTests.java, openapi-integration-tests/src/test/resources/client-idl-projects/project_13/Ballerina.toml, openapi-integration-tests/src/test/resources/client-idl-projects/project_13/main.bal, openapi-integration-tests/src/test/resources/client-idl-projects/project_13/openapi.yaml
=> Handle error message for unsupported version in swagger for IDL Client 

gradle.properties, openapi-integration-tests/src/test/java/io/ballerina/openapi/idl/client/IDLClientGenPluginNegativeTests.java
=> Update dependency versions

openapi-client-idl-plugin/src/main/java/io/ballerina/openapi/idl/client/Constants.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/idl/client/IDLClientGenPluginTests.java, openapi-integration-tests/src/test/resources/client-idl-projects/project_14/Ballerina.toml, openapi-integration-tests/src/test/resources/client-idl-projects/project_14/main.bal, openapi-integration-tests/src/test/resources/client-idl-projects/project_14/openapi.json
=> Fix IDL client generation for openAPI JSON definitions

gradle.properties
=> Update with HTTP timestamped version

gradle.properties
=> [2201.2.3-rc1]Update ballerina lang version

openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/ArrayTypeGenerator.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/SchemaGenerationTests.java, openapi-integration-tests/src/test/resources/schema/array.bal, openapi-integration-tests/src/test/resources/schema/array.yaml
=> Fix avoid constraint generation for array items when it has nullable enable flag

openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/ArrayTypeGenerator.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/SchemaGenerationTests.java, openapi-integration-tests/src/test/resources/schema/array.bal, openapi-integration-tests/src/test/resources/schema/array.yaml
Fix #1090 
Master PR: https://github.com/ballerina-platform/openapi-tools/pull/1099
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.
> Link to drafts …
=> [1.2.x] Fix avoid constraint generation for array items when it has nullable enable flag

gradle.properties
=> Update Ballerina lang version `2201.2.3-rc2.1`

openapi-validator/src/test/java/io/ballerina/openapi/validator/tests/PreValidationTests.java
=> [1.2.x]Fix the test failure

gradle.properties
=> Update ballerina lang version to 2201.2.3

openapi-extension/src/main/java/io/ballerina/openapi/extension/doc/gen/AbstractOpenApiDocGenerator.java
> $subject
Fixes [#3613](https://github.com/ballerina-platform/ballerina-standard-library/issues/3613)
=> Remove unwanted warning log for empty open-api definition

gradle.properties
=> Update dependencies to update 3 rc2

openapi-validator/src/test/java/io/ballerina/openapi/validator/tests/PreValidationTests.java
=> Improve validator pre-validation test for checking diagnostic message

gradle.properties
=> [Sync] 1.3.x branch with latest version update

gradle.properties
=> [1.3.x] Update dependency versions with 2201.3.0-rc3 lang version

gradle.properties
=> [1.3.x] Update Ballerina lang version to `2201.3.0`

gradle.properties, module-ballerina-openapi/CompilerPlugin.toml, openapi-validator/src/test/resources/pre-processing/multiple_services.bal
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517 …
=> Fix failing build for type-reference support

module-ballerina-openapi/CompilerPlugin.toml
=> Remove unwanted version update

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RecordTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/TestUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/AnyOfDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/OneOfDataTypeTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/union_with_nullable.yaml
Fixes https://github.com/ballerina-platform/openapi-tools/issues/590 …
=> [master] Improve schema generation logic for union types containing the nil type

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RecordTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/TestUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/AnyOfDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/OneOfDataTypeTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/union_with_nullable.yaml
Fixes https://github.com/ballerina-platform/openapi-tools/issues/590 …
=> [1.3.x] Improve schema generation logic for union types containing the nil type

gradle.properties
=> [1.3.x]Update dependency versions and Ballerina lang version

openapi-cli/src/test/resources/generators/schema/ballerina/nullable_anyof_array_schema.bal, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/UnionTypeGenerator.java
Fixes https://github.com/ballerina-platform/openapi-tools/issues/810 …
=> [1.3.x] Improve union type creation logic in Ballerina record generation

openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestUtils.java, openapi-cli/src/test/resources/generators/client/ballerina/multipart_formdata.bal, openapi-cli/src/test/resources/generators/client/utils/swagger/multipart_formdata.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/MultipartFormData.java
Fixes https://github.com/ballerina-platform/openapi-tools/issues/895 …
=> [1.3.x] Fix client generation for `multipart/formdata` with no encoding options

openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestUtils.java, openapi-cli/src/test/resources/generators/client/ballerina/multipart_formdata.bal, openapi-cli/src/test/resources/generators/client/utils/swagger/multipart_formdata.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/MultipartFormData.java
Fixes https://github.com/ballerina-platform/openapi-tools/issues/895 …
=> [master] Fix client generation for multipart/formdata with no encoding options

gradle.properties
=> [1.3.x]Update Ballerina Lang version 2201.3.2-rc1

build.gradle, gradle.properties, gradle/javaProject.gradle, openapi-bal-service/build.gradle, openapi-build-extension/build.gradle, openapi-cli/build.gradle, openapi-cli/src/main/java/module-info.java, openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java, openapi-cli/src/test/resources/expected_gen/petstore_client_swagger.bal, openapi-cli/src/test/resources/expected_gen/petstore_service_swagger.bal, openapi-cli/src/test/resources/petstore_swagger.yaml, openapi-cli/src/test/resources/petstore_swagger_1.2.json, openapi-client-idl-plugin/build.gradle, openapi-core/build.gradle, openapi-core/src/main/java/io/ballerina/openapi/core/ErrorMessages.java, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java, openapi-core/src/main/java/module-info.java, openapi-integration-tests/build.gradle, openapi-ls-extension/build.gradle, openapi-validator/build.gradle
> $subject
resolves https://github.com/ballerina-platform/openapi-tools/issues/1091
> Java JDK 11
=> Add support for swagger 2.0

gradle.properties
=> [1.3.x]Update Ballerina lang version 2201.3.2-rc.1

gradle.properties
=> Update lang version for 1.3.1 release

openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_0102_rb.bal, openapi-cli/src/test/resources/generators/service/swagger/requestBody/scenario01_02_rb.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/MimeFactory.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/CustomType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/JsonType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/MimeType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/OctetStreamType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/UrlEncodedType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/XmlType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ParametersGenerator.java
Fixes https://github.com/ballerina-platform/openapi-tools/issues/815 …
=> [master] Fix NPE in service generation for octet-stream content type with schemas

openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_0102_rb.bal, openapi-cli/src/test/resources/generators/service/swagger/requestBody/scenario01_02_rb.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/MimeFactory.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/CustomType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/JsonType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/MimeType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/OctetStreamType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/UrlEncodedType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/XmlType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ParametersGenerator.java
Fixes https://github.com/ballerina-platform/openapi-tools/issues/815 …
=> [1.3.x] Fix NPE in service generation for octet-stream content type with schemas

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/compiler_warning.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/escape_identifier_02.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/cache_config_06.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/no_body_field.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario09.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario20.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/status_code/not_acceptable.yaml
=> [master] Fix wrong description for 500 status code

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/HttpMethodTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ResponseTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/escape_identifier_02.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/post_method.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/cyclic_record.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/with_read_only_keyword.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario09.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario10.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario11.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario17.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario18.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response02.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/post_method.bal
> Fix #https://github.com/ballerina-platform/openapi-tools/issues/1152
- Integration tests 
> JDK 11
=> [1.3.x]Fix  POST method status code 201 mapping issue in OAS Spec generation

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/HttpMethodTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ResponseTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/escape_identifier_02.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/post_method.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/cyclic_record.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/with_read_only_keyword.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario09.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario10.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario11.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario17.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario18.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response02.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/post_method.bal
> Fix https://github.com/ballerina-platform/openapi-tools/issues/1152
Related PR: https://github.com/ballerina-platform/openapi-tools/pull/1162
> List all JDK versions, operating systems, databases, and browser/versions on which …
=> [master] Fix POST method status code 201 mapping issue in OAS Spec generation

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/compiler_warning.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/escape_identifier_02.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/cache_config_06.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/no_body_field.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario09.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario20.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/status_code/not_acceptable.yaml
=> [1.3.x] Fix wrong description for 500 status code

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ModuleReferenceTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/ballerina-project/service/modules/representations/representations.bal, openapi-cli/src/test/resources/ballerina-to-openapi/ballerina-project/service/readonly.bal, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/readonly.yaml
> Fix #https://github.com/ballerina-platform/openapi-tools/issues/1151
Master PR: https://github.com/ballerina-platform/openapi-tools/pull/1173
=> [1.3.x]Add fix for mapping readonly record in separate module to Ballerina to OpenAPI spec generation

gradle.properties
=> [Update 04]Update Ballerina lang and Dependency versions

openapi-cli/src/test/java/io/ballerina/openapi/generators/service/RequestBodyTests.java, openapi-cli/src/test/resources/expected_gen/petstore_service_swagger.bal, openapi-cli/src/test/resources/expected_gen/petstore_wildcard_service.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/multipart_form_data.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/oneof_requestBody.bal, openapi-cli/src/test/resources/generators/service/swagger/requestBody/multipart_form_data.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/RequestBodyGenerator.java
> Fix [#982 ](https://github.com/ballerina-platform/openapi-tools/issues/884)
> Handle multipart form data handling in request body payload in service generation
```openapi
openapi: 3.0.1
info:
title: testInlineRequestBody
version: 1.0.0
paths:
/user:
post:
summary: Post operation for the path /user
operationId: addUser
requestBody:
content:
multipart/form-data:
schema:
type: object
properties:
userName:
description: User Name
type: string
userPhone:
description: User Phone Number
type: string
required:
- userName
- userPhone
responses:
200:
description: Successful
content:
example: Ok
components: {}
```
Generated code
```ballerina
listener http:Listener ep0 = new (9090, config = {host: "localhost"});
service / on ep0 {
resource function post …
```
=> [master] Fix service generation when operation has request body with multipart form data payload type

openapi-core/src/main/java/io/ballerina/openapi/core/model/GenSrcFile.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1185 …
=> [1.4.x] Fix util file not over-writing bug

gradle.properties
=> Update the Ballerina lang and dependency versions

openapi-core/src/main/java/io/ballerina/openapi/core/model/GenSrcFile.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1185 in OpenAPI tools 1.3.x branch
> Link to the …
=> [1.3.x] Fix util file not over-writing bug

gradle.properties
=> Update the Ballerina Lang version 2201.4.0

gradle.properties
=> [1.3.x] Update lang version for  2201.3.3-rc1

gradle.properties
=> Update std lib versions for 2201.3.3-rc1

.github/workflows/pull-request.yml, build.gradle
=> Add sonar-cloud support

gradle.properties
=> Update HTTP and Oauth2 timestamped versions

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ResponseTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/TestUtils.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/same_status_code.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/response/same_status_code.bal, openapi-cli/src/test/resources/expected_gen/same_status_code.yaml
> Fix #https://github.com/ballerina-platform/openapi-tools/issues/982 …
=> Fix to handle multiple responses with same code

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/BallerinaToOpenAPITests.java, openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation/Ballerina.toml, openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation/result.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation/service.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_with_base_path/Ballerina.toml, openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_with_base_path/result.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_with_base_path/service.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_without_base_path/Ballerina.toml, openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_without_base_path/result.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_without_base_path/service_file.bal
=> [1.4.x]Fix for OpenAPI spec generation when display annotations are used

openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/PrimitiveTypeGenerator.java, openapi-core/src/main/resources/templates/utils_openapi.bal
> Fix bugs in multipart/form-data mimetype request bodies with file upload
> Java JDK 11
=> [openai-fixes-1.4.x] Fix bug in multipart/form-data

openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/ConstraintTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/nested_array.bal, openapi-cli/src/test/resources/generators/schema/swagger/constraint/nested_array_with_constraint.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/BallerinaTypesGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/ArrayTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/RecordTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/TypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/UnionTypeGenerator.java
=> [1.4.x]Fix issue with nested array types with constraint value

openapi-cli/src/test/resources/generators/schema/ballerina/default_optional_string_schema.bal, openapi-cli/src/test/resources/generators/schema/swagger/default_optional_string_schema.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/TypeGeneratorUtils.java
=> [openapi-fixes-1.4.x] Fix for default value assign in oneOf schema

openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java, openapi-cli/src/test/resources/expected_gen/non_constraint_import_types.bal, openapi-cli/src/test/resources/non_constraint_import.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
=> [openapi-fixes-1.4.x]Fix for remove unnecessary constraint import from `type.bal` 

openapi-cli/src/test/resources/generators/schema/ballerina/default_optional_primitive_schema.bal, openapi-cli/src/test/resources/generators/schema/swagger/default_optional_primitive_schema.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/TypeGeneratorUtils.java
> $Subject
> When the given schema has a boolean default value it should be mapped to a boolean in ballerina. 
```openapi
type:
type: string
isTrue:
type: boolean
default: true
```
ballerina
```ballerina
string 'type?;
boolean isTrue = true;
```
Note: Still remaining to support default value mapping structured type (ex: Record) in openapi to ballerina .
> Link(s) to product …
=> [openapi-fixes-1.4.x] Fix for default value assign in boolean schema

openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/NullableFieldTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/null_empty_record.bal, openapi-cli/src/test/resources/generators/schema/swagger/null_empty_record.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/RecordTypeGenerator.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1227 …
=> [openai-fixes-1.4.x] Bug fix in nullable empty object schema generation

openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/ConstraintTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/NullableFieldTests.java, openapi-cli/src/test/resources/expected_gen/non_constraint_import_types.bal, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/nested_array.bal, openapi-cli/src/test/resources/generators/schema/ballerina/default_optional_primitive_schema.bal, openapi-cli/src/test/resources/generators/schema/ballerina/default_optional_string_schema.bal, openapi-cli/src/test/resources/generators/schema/ballerina/null_empty_record.bal, openapi-cli/src/test/resources/generators/schema/swagger/constraint/nested_array_with_constraint.yaml, openapi-cli/src/test/resources/generators/schema/swagger/default_optional_primitive_schema.yaml, openapi-cli/src/test/resources/generators/schema/swagger/default_optional_string_schema.yaml, openapi-cli/src/test/resources/generators/schema/swagger/null_empty_record.yaml, openapi-cli/src/test/resources/non_constraint_import.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/BallerinaTypesGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/TypeGeneratorUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/ArrayTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/PrimitiveTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/RecordTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/TypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/UnionTypeGenerator.java, openapi-core/src/main/resources/templates/utils_openapi.bal
=> Update 1.4.x branch with openAI related fixes

gradle.properties, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIParameterMapper.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/OASContractGenerator.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ParameterAnnotationTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/parameter_annotation/annotated_payload_complex.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/parameter_annotation/annotated_query.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/parameter_annotation/unannotated_payload.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/parameter_annotation/annotated_payload_complex.bal, openapi-cli/src/test/resources/ballerina-to-openapi/parameter_annotation/annotated_query.bal, openapi-cli/src/test/resources/ballerina-to-openapi/parameter_annotation/invalid_payload.bal, openapi-cli/src/test/resources/ballerina-to-openapi/parameter_annotation/unannotated_payload.bal, openapi-cli/src/test/resources/testng.xml
> Resolves https://github.com/ballerina-platform/openapi-tools/issues/1196
> Please refer to the document [here](https://docs.google.com/document/d/1CnSCMDhw1ftHQzgHFm6xJ1nkZvA3r3x12x5Mpn3787k/edit?usp=sharing)
> Java JDK 11
=> Add support for new http payload annotation fix

openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/ConstraintTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/additional_properties_with_constraint.bal, openapi-cli/src/test/resources/generators/schema/swagger/constraint/additional_properties_with_constraint.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/ArrayTypeGenerator.java
=> [1.4.x] Fix Null Pointer exception when generating Stripe connector

openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java, openapi-cli/src/test/resources/constraint_import.yaml, openapi-cli/src/test/resources/expected_gen/constraint_import_types.bal, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
> This fix for fixing issues that introduces regression through this PR https://github.com/ballerina-platform/openapi-tools/pull/1226
Fix https://github.com/ballerina-platform/openapi-tools/issues/1237
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> [1.4.x]Fix for adding necessary constraint import

gradle.properties
=> [1.4.x] Update lang version in 1.4.x

gradle.properties
=> Update OpenAPI version to 1.5.0-SNAPSHOT

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RequestBodyTest.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ResponseTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/service_config_with_cors.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/service_config_with_cors.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/request_body/service_config_with_cors.bal, openapi-cli/src/test/resources/ballerina-to-openapi/response/service_config_with_cors.bal
>  Fix #https://github.com/wso2-enterprise/internal-support-ballerina/issues/294 …
=> [1.4.x]Fix for assigning wrong custom mediatype when the service configuration has `cors` field only

openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/FieldGenWithNullableOption.java, openapi-cli/src/test/resources/expected_gen/nullable_false_types.bal, openapi-cli/src/test/resources/expected_gen/nullable_types.bal, openapi-cli/src/test/resources/generators/schema/ballerina/additional_properties_composed_schema.bal, openapi-cli/src/test/resources/generators/schema/ballerina/additional_properties_negative.bal, openapi-cli/src/test/resources/generators/schema/ballerina/additional_properties_true.bal, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/record_field_02.bal, openapi-cli/src/test/resources/generators/schema/ballerina/null_empty_record.bal, openapi-cli/src/test/resources/generators/schema/ballerina/nullable_anyof_array_schema.bal, openapi-cli/src/test/resources/generators/schema/ballerina/nullable_anyof_schema.bal, openapi-cli/src/test/resources/generators/schema/ballerina/nullable_array.bal, openapi-cli/src/test/resources/generators/schema/ballerina/nullable_false.bal, openapi-cli/src/test/resources/generators/schema/ballerina/nullable_option_primitive_fields.bal, openapi-cli/src/test/resources/generators/schema/ballerina/nullable_option_record_schema.bal, openapi-cli/src/test/resources/generators/schema/ballerina/nullable_primitive.bal, openapi-cli/src/test/resources/generators/schema/ballerina/nullable_record.bal, openapi-cli/src/test/resources/generators/schema/ballerina/nullale_option_array_schema.bal, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/TypeGeneratorUtils.java, openapi-integration-tests/src/test/resources/schema/array.bal
=> [1.4.x] Revert "Nillable type revamp

openapi-cli/src/test/java/io/ballerina/openapi/generators/client/PathParameterTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/ResourceFunctionTests.java, openapi-cli/src/test/resources/generators/client/ballerina/union_path_parameter.bal, openapi-cli/src/test/resources/generators/client/ballerina/union_path_types.bal, openapi-cli/src/test/resources/generators/client/resource/ballerina/reference_path.bal, openapi-cli/src/test/resources/generators/client/resource/swagger/reference_path.yaml, openapi-cli/src/test/resources/generators/client/swagger/allOf_path_parameter.yaml, openapi-cli/src/test/resources/generators/client/swagger/union_path_parameter.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java
> Fix 
#1229 
https://github.com/ballerina-platform/openapi-tools/issues/1247 …
=> [1.4.x] Add fix for path parameter reference resolve

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ResponseTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/service_config_with_cors_with_slash.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/service_config_with_cors_without_base_path.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/response/service_config_with_cors_with_slash.bal, openapi-cli/src/test/resources/ballerina-to-openapi/response/service_config_with_cors_without_base_path.bal
>  When the ballerina service has slash `/` as the base path we required to fill the generated OAS with the ballerina file name
Fix #https://github.com/ballerina-platform/openapi-tools/issues/1252
```ballerina
@http:ServiceConfig {
cors: {
allowOrigins: ["*"]
}
}
service / on new http:Listener(9090) {
resource function get greeting(string name) returns string|error {
// Send a response back to the caller.
if name is "" {
return error("name should not be empty!");
}
return "Hello, " + name;
}
}
```
Generated OAS
```openapi
openapi: 3.0.1
info:
title: "/"
version: 0.0.0
servers:
- url: "{server}:{port}/"
variables:
server:
default: http://localhost
port:
default: "9090"
paths:
/greeting:
get:
summary: A resource for generating greetings
operationId: getGreeting …
```
=> [1.4.x]Add fix issue with setting value to openAPI title section

gradle.properties
=> Update gradle.properties versions for Ballerina release 2201.5.x

openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/AllOfDataTypeTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/nested_all_of.bal, openapi-cli/src/test/resources/generators/schema/swagger/nested_allOf_with_allOf.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java
> Fix #1257 
This issue occurred because of regression with referenceName resolver in allOf schema
Fix was tested with the below client generation :
- https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/bitbucket
- https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/beezup.merchant
- https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/zoom
> Summary of …
=> [1.4.x] Fix for NPE when schema has allOf reference

gradle.properties
=> [2201.5.0] Update Ballerina Lang and Dependency Versions

openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/AllOfDataTypeTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/nested_all_of.bal, openapi-cli/src/test/resources/generators/schema/swagger/nested_allOf_with_allOf.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java
> Related PR : https://github.com/ballerina-platform/openapi-tools/pull/1276
Fix https://github.com/ballerina-platform/openapi-tools/issues/1257
This issue occurred because of regression with referenceName resolver in allOf schema
Fix was tested with the below client generations :
- https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/bitbucket
- https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/beezup.merchant
- https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/zoom
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to …
=> [master] Fix for NPE when schema has allOf reference

openapi-cli/src/test/java/io/ballerina/openapi/generators/client/BallerinaDiagnosticTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java, openapi-cli/src/test/resources/generators/client/ballerina/vendor_specific_json.bal, openapi-cli/src/test/resources/generators/client/ballerina/vendor_specific_with_subtype.bal, openapi-cli/src/test/resources/generators/client/diagnostic_files/vendor_specific_mime_types.yaml, openapi-cli/src/test/resources/generators/client/swagger/vendor_specific_with_subtype.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/MimeFactory.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1265 …
=> [1.4.x] Bug fix in vendor specific mime types

openapi-cli/src/test/java/io/ballerina/openapi/generators/auth/HttpConfigurationExtensionTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestConstants.java, openapi-cli/src/test/resources/generators/client/auth/scenarios/http_config_extension/petstore_with_http_version.yaml, openapi-cli/src/test/resources/generators/client/auth/scenarios/http_config_extension/petstore_with_invalid_http_version.yaml, openapi-cli/src/test/resources/testng.xml, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/BallerinaAuthConfigGenerator.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1270 …
=> [1.4.x] Add OpenAPI extension to define http version

openapi-cli/src/test/java/io/ballerina/openapi/generators/auth/HttpConfigurationExtensionTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestConstants.java, openapi-cli/src/test/resources/generators/client/auth/scenarios/http_config_extension/petstore_with_http_version.yaml, openapi-cli/src/test/resources/generators/client/auth/scenarios/http_config_extension/petstore_with_invalid_http_version.yaml, openapi-cli/src/test/resources/testng.xml, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/BallerinaAuthConfigGenerator.java
> Send fix for https://github.com/ballerina-platform/openapi-tools/issues/1270 to master branch
Duplicate of the PR https://github.com/ballerina-platform/openapi-tools/pull/1272
https://github.com/ballerina-platform/openapi-tools/pull/1272
=> [1.5.x] Add OpenAPI extension to define http version

openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/RequestBodyTests.java, openapi-cli/src/test/resources/generators/client/ballerina/request_body_has_object_content_without_property.bal, openapi-cli/src/test/resources/generators/client/swagger/request_body_has_object_content_without_property.yaml, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/content_schema_null.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/request_body_has_object_content_without_property.bal, openapi-cli/src/test/resources/generators/service/swagger/requestBody/content_schema_null.yaml, openapi-cli/src/test/resources/generators/service/swagger/requestBody/request_body_has_object_content_without_property.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/RequestBodyGenerator.java
> Fix the Issue https://github.com/wso2-enterprise/internal-support-ballerina/issues/306#issuecomment-1498710422
https://github.com/wso2-enterprise/internal-support-ballerina/issues/306
- include a fix for the requestBody has content type schema is null
- include the fix for the requestBody has content type object without property
Reference PR : https://github.com/ballerina-platform/openapi-tools/pull/1300
=> [1.3.x] Fix for getting NPE when Ballerina service and client generation

openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/AnyOfDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/ConstraintTests.java, openapi-cli/src/test/resources/expected_gen/ballerina_project/service_type.bal, openapi-cli/src/test/resources/generators/client/ballerina/request_body_has_object_content_without_property.bal, openapi-cli/src/test/resources/generators/client/swagger/request_body_has_object_content_without_property.yaml, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/allow_zero_values_for_number_constraint.bal, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/invalidAndValidConstraintFieldWithDtaType.bal, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/invalidConstraintFieldWithDtaType.bal, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/record_field_02.bal, openapi-cli/src/test/resources/generators/schema/swagger/constraint/allow_zero_values_for_number_constraint.yaml, openapi-cli/src/test/resources/generators/schema/swagger/constraint/invalidAndValidConstraintFieldWithDataType.yaml, openapi-cli/src/test/resources/generators/schema/swagger/constraint/invalidConstraintFieldWithDataType.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/BallerinaTypesGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/TypeGeneratorUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/ArrayTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/RecordTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/TypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/UnionTypeGenerator.java
> Fix #1278 
#1291 
https://github.com/wso2-enterprise/internal-support-ballerina/issues/306
Related PRs : https://github.com/ballerina-platform/openapi-tools/pull/1300
https://github.com/ballerina-platform/openapi-tools/pull/1303
> Link(s) to product documentation that addresses the …
=> [1.5.x] Fixes for NPE in client generation and avoid adding unnecessary `constraint` imports

openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/PrimitiveDataTypeTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/additional_properties_invalid_format.bal, openapi-cli/src/test/resources/generators/schema/swagger/additional_properties_invalid_format.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/RecordTypeGenerator.java
> Send fix for https://github.com/ballerina-platform/openapi-tools/issues/1285 to 1.5.x branch
Duplicate of the PR https://github.com/ballerina-platform/openapi-tools/pull/1296
https://github.com/ballerina-platform/openapi-tools/pull/1296
=> [1.5.x] Bug fix in additional property mapping when invalid number format is given

gradle.properties
=> [1.4.x] Update task version

gradle.properties
=> [1.3.x] Update Ballerina lang version

gradle.properties
=> [1.3.x] Update Dependency versions 

openapi-cli/src/test/java/io/ballerina/openapi/generators/client/ComparedGeneratedFileTests.java, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/multiline_param_comment.bal, openapi-cli/src/test/resources/generators/client/file_provider/swagger/multiline_param_comment.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/document/DocCommentsGenerator.java
> $subject
Duplicate PR of https://github.com/ballerina-platform/openapi-tools/pull/1268
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1267
=> [1.5.x] Add support for multi-line parameter descriptions

openapi-cli/src/test/java/io/ballerina/openapi/generators/client/ComparedGeneratedFileTests.java, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/multiline_param_comment.bal, openapi-cli/src/test/resources/generators/client/file_provider/swagger/multiline_param_comment.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/document/DocCommentsGenerator.java
> $subject
Duplicate PR of https://github.com/ballerina-platform/openapi-tools/pull/1268
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1267
=> [master] Add support for multi-line parameter descriptions

openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ReturnTypeTests.java, openapi-cli/src/test/resources/generators/service/ballerina/response/multiline_return_description.bal, openapi-cli/src/test/resources/generators/service/swagger/response/multiline_return_description.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ReturnTypeGenerator.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1344 …
=> Bug fix in service generation with multi line return type descriptions

gradle.properties
=> Update dependency version according to graphQL module

openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ReturnTypeTests.java, openapi-cli/src/test/resources/generators/service/ballerina/response/multiline_return_description.bal, openapi-cli/src/test/resources/generators/service/swagger/response/multiline_return_description.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ReturnTypeGenerator.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1344
Duplicate of https://github.com/ballerina-platform/openapi-tools/pull/1345  …
=> [master] Bug fix in service generation with multi line return type descriptions

gradle.properties, openapi-cli/src/main/java/io/ballerina/openapi/cmd/OpenApiCmd.java, openapi-cli/src/main/resources/ballerina-openapi.help, openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java
=> [master]Fix for migrating help text display logic into OpenAPI repo form Ballerina Lang

gradle.properties
=> Update dependency versions and Ballerina lang version

gradle.properties
=> Update OpenAPI version in master to 1.7.0

openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
=> [1.6.x]Add new line to end of the warning message

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java
>  Handle query parameter https://github.com/ballerina-platform/openapi-tools/issues/1329  …
=> Add enum support in openapi generation

gradle.properties
=> [1.5.X-object-query]Update dependency version according to http module

gradle.properties
=> [1.5.x]Update Ballerina lang version

gradle.properties
=> [1.7.x]Update Ballerina lang and dependency versions

gradle.properties
=> [1.7.x] Update dependency versions  

openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIConverterService.java
$subject
>  Resolves https://github.com/ballerina-platform/openapi-tools/issues/1401 …
=> [1.5.x] Bug fix in loading resource function params in vs-code swagger view

openapi-cli/src/test/java/io/ballerina/openapi/generators/service/QueryParameterTests.java, openapi-cli/src/test/resources/generators/service/ballerina/parameters_with_object_ref_schema.bal, openapi-cli/src/test/resources/generators/service/swagger/parameters_with_ref_schema.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ParametersGenerator.java
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves https://github.com/ballerina-platform/openapi-tools/issues/1417
> Java JDK 11
=> [1.7.x] Bug fix in array type query parameters with referenced schema

openapi-cli/src/test/java/io/ballerina/openapi/generators/service/QueryParameterTests.java, openapi-cli/src/test/resources/generators/service/ballerina/parameters_with_object_ref_schema.bal, openapi-cli/src/test/resources/generators/service/swagger/parameters_with_ref_schema.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ParametersGenerator.java
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves https://github.com/ballerina-platform/openapi-tools/issues/1417
> Java JDK 11
https://github.com/ballerina-platform/openapi-tools/pull/1419
=> [1.6.x] Bug fix in array type query parameters with referenced schema

openapi-cli/src/test/java/io/ballerina/openapi/generators/service/RequestBodyTests.java, openapi-cli/src/test/resources/expected/petstore_catch_all_path.bal, openapi-cli/src/test/resources/expected_gen/petstore_service_swagger.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/additional_prop_types.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/additional_property.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_02_rb.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_03_rb.bal, openapi-cli/src/test/resources/generators/service/swagger/requestBody/additional_property.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/RequestBodyGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ServiceGenerationUtils.java
Fix #https://github.com/ballerina-platform/openapi-tools/issues/1411
Doc: https://docs.google.com/document/d/1RTM1HdwoolSIYWpy4I_3OUnpSxwgzI68iAATwLWXyoo/edit#heading=h.1nhlfl98hes6
=> [1.5.x] Add fix for handling `additionalProperties` field in requestBody in service generation

openapi-cli/src/test/java/io/ballerina/openapi/generators/service/RequestBodyTests.java, openapi-cli/src/test/resources/expected/petstore_catch_all_path.bal, openapi-cli/src/test/resources/expected_gen/petstore_service_swagger.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/additional_prop_types.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/additional_property.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_02_rb.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_03_rb.bal, openapi-cli/src/test/resources/generators/service/swagger/requestBody/additional_property.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/RequestBodyGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ServiceGenerationUtils.java
> Fix https://github.com/ballerina-platform/openapi-tools/issues/1411
Reference PR: https://github.com/ballerina-platform/openapi-tools/pull/1414
=> [1.6.x] Add fix for handling `additionalProperties` field in requestBody in service generation

openapi-cli/src/test/java/io/ballerina/openapi/generators/service/RequestBodyTests.java, openapi-cli/src/test/resources/expected/petstore_catch_all_path.bal, openapi-cli/src/test/resources/expected_gen/petstore_service_swagger.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/additional_prop_types.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/additional_property.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_02_rb.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/scenario_03_rb.bal, openapi-cli/src/test/resources/generators/service/swagger/requestBody/additional_property.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/RequestBodyGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ServiceGenerationUtils.java
> Fix https://github.com/ballerina-platform/openapi-tools/issues/1411
Reference PR: https://github.com/ballerina-platform/openapi-tools/pull/1414
=> [1.7.x] Add fix for handling `additionalProperties` field in requestBody in service generation

gradle.properties
=> [1.6.x]Update openAPI tool version

openapi-extension/src/main/java/io/ballerina/openapi/extension/context/OpenApiDocContextHandler.java, spotbugs-exclude.xml
=> Fix spotbugs issues

module-ballerina-openapi/build.gradle
=> Fix gradle build

gradle.properties
=> [1.6.x]Update ballerina lang and dependency versions for Ballerina 2201.6.1 release

openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java, openapi-cli/src/test/resources/expected/petstore_catch_all_path.bal, openapi-cli/src/test/resources/expected_gen/petstore_catch_all_path_client.bal, openapi-cli/src/test/resources/generators/service/ballerina/headers/header_01.bal, openapi-cli/src/test/resources/generators/service/ballerina/headers/header_06.bal, openapi-cli/src/test/resources/generators/service/ballerina/headers/header_07.bal, openapi-cli/src/test/resources/generators/service/ballerina/headers/header_08.bal, openapi-cli/src/test/resources/generators/service/ballerina/headers/header_09.bal, openapi-cli/src/test/resources/generators/service/ballerina/headers/header_10.bal, openapi-cli/src/test/resources/generators/service/ballerina/headers/header_11.bal, openapi-cli/src/test/resources/generators/service/ballerina/headers/header_12.bal, openapi-cli/src/test/resources/generators/service/ballerina/headers/header_parameters.bal, openapi-cli/src/test/resources/generators/service/ballerina/listeners/listeners05.bal, openapi-cli/src/test/resources/generators/service/ballerina/path_parameters03.bal, openapi-cli/src/test/resources/generators/service/ballerina/requestBody/refactor_record_name.bal, openapi-cli/src/test/resources/generators/service/ballerina/response/path_with_special_characters.bal, openapi-cli/src/test/resources/generators/service/ballerina/service_gen_special_characters.bal, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java
> Fix # https://github.com/wso2-enterprise/internal-support-ballerina/issues/360
> Describe the research phase and any …
=> [1.5.x]Removing unnecessary `'` from modified type, variable name after escaping special characters 

openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionReturnTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/EnumGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/PrimitiveTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/RecordTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ServiceGenerationUtils.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/TestUtil.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/ServiceGenerationTests.java, openapi-integration-tests/src/test/resources/service/return/swagger/unsupported_oas_format.yaml, openapi-integration-tests/src/test/resources/testng.xml
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1412
> Print a warning meesage when unsupported data format is given in the OpenAPI file
Fix was sent to address the unsupported data type format scenarios by priniting a warning message in the CLI without terminating the generation purpose. The format would not be considered in generation and the type will be used to identify the corresponsing ballerina type.
Ex:
```yaml
components:
schemas:
Pet:
required:
- id
- name
properties:
id:
type: integer
format: int64
price:
type: number
format: currency
name:
type: string
tag:
type: string
type:
type: string
updatedDate:
type: string
format: date
additionalProperties: false
```
**In 2201.5.1 :**
Generation terminated with the error message 
```Error occurred when …
```
=> [1.6.x] Handle unsupported data type formats

openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionReturnTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/EnumGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/PrimitiveTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/RecordTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ServiceGenerationUtils.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/TestUtil.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/ServiceGenerationTests.java, openapi-integration-tests/src/test/resources/service/return/swagger/unsupported_oas_format.yaml, openapi-integration-tests/src/test/resources/testng.xml
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1412
Duplicate of the PR https://github.com/ballerina-platform/openapi-tools/pull/1437
> [List any other related PRs](https://github.com/ballerina-platform/openapi-tools/pull/1437)
> Java JDK 11
=> [1.7.x] Handle unsupported data type formats

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/catch_all_path_service.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/compiler_warning.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/escape_identifier_02.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/request_body/service_config_with_cors.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/cache_config_06.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/no_body_field.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario09.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/rs_scenario20.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/same_status_code.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/service_config_with_cors.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/service_config_with_cors_with_slash.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/response/service_config_with_cors_without_base_path.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/status_code/not_acceptable.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation/result.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_with_base_path/result.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_non_openapi_annotation_without_base_path/result.yaml
> https://github.com/ballerina-platform/openapi-tools/issues/1407 …
=> [1.7.x]Fix for improving the error message content mapping according to changes from HTTP module

gradle.properties
=> [1.7.x]Update ballerina lang version

README.md, build.gradle, gradle/javaProject.gradle
=> Update Java version

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java
> $subject
Resolve https://github.com/ballerina-platform/openapi-tools/issues/1459
> https://github.com/ballerina-platform/ballerina-lang/pull/39585
=> Support new changes in the semantics of intersection

gradle.properties
=> [master] Update graphQL version

gradle.properties, module-ballerina-openapi/Ballerina.toml, module-ballerina-openapi/CompilerPlugin.toml
=> Update lang version

build.gradle
=> Fix dependency issues on code coverage report task

gradle.properties
> $Subject
This is for getting the language changes related to subtypes
https://github.com/ballerina-platform/ballerina-lang/pull/40942
=> [TypeInclusion-Fix] Update Ballerina Lang version

openapi-cli/src/test/java/io/ballerina/openapi/generators/client/BallerinaDiagnosticTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ServiceDiagnosticTests.java
=> [TypeInclusion]Disable tests for creating the pack

openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIConverterService.java
https://github.com/wso2-enterprise/ballerina-plugin-vscode/issues/1815#issuecomment-1663355099\
> Link(s) to product …
=> [1.7.x]Fix to resolve a vs-code bug

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RecordTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/cyclic_record_with_typeInclusion.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/typeref_records_with_interdependency.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/union_records_with_interdependency.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/record/cyclic_record_with_typeInclusion.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/typeref_records_with_interdependency.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/union_records_with_interdependency.bal
>  fix #https://github.com/wso2-enterprise/internal-support-ballerina/issues/390
https://github.com/ballerina-platform/openapi-tools/issues/1471
https://github.com/ballerina-platform/openapi-tools/issues/1470
> Link(s) to product documentation that addresses the changes of this PR. If …
=> [1.7.x] Fix for stackoverflow error when records have interdependencies

gradle.properties
=> [1.7.x] Update Ballerina lang version

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/RecordTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/cyclic_record_with_typeInclusion.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/typeref_records_with_interdependency.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/union_records_with_interdependency.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/record/cyclic_record_with_typeInclusion.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/typeref_records_with_interdependency.bal, openapi-cli/src/test/resources/ballerina-to-openapi/record/union_records_with_interdependency.bal
> fix #https://github.com/wso2-enterprise/internal-support-ballerina/issues/390
https://github.com/ballerina-platform/openapi-tools/issues/1471
https://github.com/ballerina-platform/openapi-tools/issues/1470
Related PR: https://github.com/ballerina-platform/openapi-tools/pull/1486
=> [master] Fix for stackoverflow error when records have interdependencies

gradle.properties, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/BallerinaDiagnosticTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ServiceDiagnosticTests.java
> Related issue https://github.com/ballerina-platform/openapi-tools/issues/1440
=> [master] Disable the `beezup` connector diagnostic tests

openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIConverterService.java
> Duplicate of https://github.com/ballerina-platform/openapi-tools/pull/1487
=> [master] Fix to resolve a vs-code bug

openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIConverterService.java
> $subject
> https://github.com/ballerina-platform/openapi-tools/pull/1487
> LJDK 11
=> [1.7.x] Fix bug in `try it` code-lense not working for record type payload parameters

openapi-ls-extension/src/main/java/io/ballerina/openapi/extension/OpenAPIConverterService.java
> Resolves https://github.com/ballerina-platform/openapi-tools/issues/1500
Duplicate PR of https://github.com/ballerina-platform/openapi-tools/pull/1499
=> [master] Fix bug in try it code-lense not working for record type payload parameters

openapi-cli/src/test/java/io/ballerina/openapi/generators/client/ComparedGeneratedFileTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/ConstraintTests.java, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/format_types_v3_0.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/format_types_v3_1.bal, openapi-cli/src/test/resources/generators/client/file_provider/swagger/format_types_v3_0.yaml, openapi-cli/src/test/resources/generators/client/file_provider/swagger/format_types_v3_1.yaml, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/additional_properties_with_constraint.bal, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/format_type.bal, openapi-cli/src/test/resources/generators/schema/swagger/constraint/additional_properties_with_constraint.yaml, openapi-cli/src/test/resources/generators/schema/swagger/constraint/format_types_v3_0.yaml, openapi-cli/src/test/resources/generators/schema/swagger/constraint/format_types_v3_1.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/TypeGeneratorUtils.java
> Fixes https://github.com/ballerina-platform/openapi-tools/issues/1505
> Describe the research phase and any blog …
=> [master] Fix for avoiding invalid constraint validation for `byte[]` OpenAPI to Ballerina client generation

openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java
=> [1.5.x] Fix returning an unsupported message when an OpenAPI with unsupported version is given

openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java
=> Fix returning an unsupported message when an OpenAPI with unsupported version is given

openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/CmdConstants.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1464
> Java JDK 11
> https://github.com/ballerina-platform/openapi-tools/pull/1465
=> [1.7.x] Return an unsupported message when an OpenAPI with unsupported version is given

openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/CmdConstants.java
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1464
> Java JDK 11
> https://github.com/ballerina-platform/openapi-tools/pull/1465
=> [1.6.x] Return an unsupported message when an OpenAPI with unsupported version is given

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/CmdConstants.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/BallerinaDiagnosticTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/PathParameterTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/AllOfDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ServiceDiagnosticTests.java, openapi-cli/src/test/resources/generators/diagnostic_files/single_allOf.yaml, openapi-cli/src/test/resources/generators/schema/ballerina/single_item_allOf.bal, openapi-cli/src/test/resources/generators/schema/swagger/single_item_allOf.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java, openapi-validator/src/main/java/io/ballerina/openapi/validator/Constants.java, openapi-validator/src/test/resources/return/response_code.yaml
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1511 in 1.6.x 
> Java 11
=> [1.6.x] Handling single valid item AllOf schema in client/service generation

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/CmdConstants.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/BallerinaDiagnosticTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/PathParameterTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/AllOfDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ServiceDiagnosticTests.java, openapi-cli/src/test/resources/generators/diagnostic_files/single_allOf.yaml, openapi-cli/src/test/resources/generators/schema/ballerina/single_item_allOf.bal, openapi-cli/src/test/resources/generators/schema/swagger/single_item_allOf.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorConstants.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java, openapi-validator/src/main/java/io/ballerina/openapi/validator/Constants.java, openapi-validator/src/test/resources/return/response_code.yaml
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1511 in 1.5.x 
> Java 11
=> [1.5.x] Handling single valid item AllOf schema in client/service generation

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/CmdConstants.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/BallerinaDiagnosticTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/PathParameterTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/AllOfDataTypeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ServiceDiagnosticTests.java, openapi-cli/src/test/resources/generators/diagnostic_files/single_allOf.yaml, openapi-cli/src/test/resources/generators/schema/ballerina/single_item_allOf.bal, openapi-cli/src/test/resources/generators/schema/swagger/single_item_allOf.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java, openapi-validator/src/main/java/io/ballerina/openapi/validator/Constants.java, openapi-validator/src/test/resources/return/response_code.yaml
> $subject
Resolves https://github.com/ballerina-platform/openapi-tools/issues/1511 in master
> Java 11
=> [master] Handling single valid item AllOf schema in client/service generation

gradle.properties
=> [1.5.x] Update Ballerina lang version

gradle.properties
=> [1.6.x]Update Ballerina lang version

gradle/javaProject.gradle, openapi-bal-service/build.gradle, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIHeaderMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIQueryParameterMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java, openapi-bal-service/src/main/java/module-info.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/HeaderTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/QueryParameterTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/enum_header.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/enum_query.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/header_scenario12.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/header_scenario13.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/parameter_annotation/annotated_query.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/query/query_scenario06.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/query/query_scenario09.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/headers/header_scenario13.bal, openapi-cli/src/test/resources/ballerina-to-openapi/query/query_scenario09.bal
> $ Subject
Related to: https://github.com/wso2-enterprise/internal-support-ballerina/issues/505
=> [1.8.x] Fix default value mapping in the OAS generation

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIHeaderMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIQueryParameterMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/HeaderTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/QueryParameterTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/header_scenario12.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/header_scenario13.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/parameter_annotation/annotated_query.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/query/query_scenario06.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/query/query_scenario09.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/headers/header_scenario13.bal, openapi-cli/src/test/resources/ballerina-to-openapi/query/query_scenario09.bal
> $ Subject
Related to: https://github.com/wso2-enterprise/internal-support-ballerina/issues/505
=> [1.7.x] Fix default value mapping in the OAS generation

gradle/javaProject.gradle, openapi-bal-service/build.gradle, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIHeaderMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIQueryParameterMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java, openapi-bal-service/src/main/java/module-info.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/HeaderTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/QueryParameterTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/enum_header.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/enum_query.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/header_scenario12.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/header_scenario13.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/parameter_annotation/annotated_query.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/query/query_scenario06.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/query/query_scenario09.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/headers/header_scenario13.bal, openapi-cli/src/test/resources/ballerina-to-openapi/query/query_scenario09.bal
> $ Subject
Related to: https://github.com/wso2-enterprise/internal-support-ballerina/issues/505
=> [Master] Fix default value mapping in the OAS generation

gradle.properties
=> [1.8.x]Update Ballerina lang and dependency versions

openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java, openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenApiGenServiceCmdTest.java, openapi-cli/src/test/resources/expected_gen/without-data-binding.bal, openapi-cli/src/test/resources/withoutDataBinding.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/BallerinaClientGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/BallerinaServiceGenerator.java
> Fix #https://github.com/wso2-enterprise/internal-support-ballerina/issues/528
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable
- Unit tests  …
=> [1.5.x] Remove `types.bal` generation from low level service

openapi-bal-service/src/main/java/io/ballerina/openapi/converter/Constants.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java, openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/DataTypeTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/data_type/built_in_sub_types_in_record.bal, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/data_type/built_in_sub_types_in_record.yaml
> $Subject
Related to: https://github.com/ballerina-platform/ballerina-library/issues/5883
=> [1.7.x] Add built-in subtype support in record fields for OAS generation 

docs/ballerina-to-oas/proposals/constraint-support.md
=> [Ballerina to OAS] Add constraint support proposal to the docs

docs/ballerina-to-oas/proposals/hateoas_support.md
=> [Ballerina to OAS] Add hateoas support proposal to the docs

gradle/javaProject.gradle, openapi-cli/build.gradle, openapi-cli/src/main/java/io/ballerina/openapi/cmd/Add.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/BaseCmd.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/CmdConstants.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/CmdOptions.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/ErrorMessages.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/OpenApiCmd.java, openapi-cli/src/main/java/module-info.java, openapi-cli/src/test/java/io/ballerina/openapi/cmd/NegativeCmdTests.java, openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java, openapi-cli/src/test/resources/cmd/bal-task-client/Ballerina.toml, openapi-cli/src/test/resources/testng.xml
> Fix #https://github.com/ballerina-platform/ballerina-library/issues/5825
Parent issue: https://github.com/ballerina-platform/ballerina-library/issues/4932
we are introducing a `add` sub command to the openapi main command to update the Ballerina.toml with openapi tool options to integrate the tool to build command. 
ex: `bal openapi add -i "petstore.yaml" --module "delivery" --operations="op1","op2","op3" --mode client --nullable --license="license.txt" --client-methods=resource`
updated Ballerina.toml
```toml
[[tool.openapi]]
id = "oas_client_petstore"
filePath = "petstore.yaml"
targetModule = "delivery"
options.mode = "client"
option.operations = ["op1","op2","op3"]
options.nullable = true
options.clientMethods = "resource"
```
=> [bal-build-task] Implement  `add` command for updating Ballerina.toml with openapi tool config element

openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java, openapi-cli/src/test/resources/expected_gen/licenses/schema_for_both_service_client.bal, openapi-cli/src/test/resources/expected_gen/licenses/schema_for_service.bal, openapi-cli/src/test/resources/expected_gen/licenses/schema_with_user_given_license.bal, openapi-cli/src/test/resources/expected_gen/licenses/types_for_both_service_client_generations.bal, openapi-cli/src/test/resources/expected_gen/petstore_schema.bal, openapi-cli/src/test/resources/expected_gen/petstore_schema_type.bal, openapi-cli/src/test/resources/expected_gen/petstore_schema_with_license.bal, openapi-cli/src/test/resources/expected_gen/petstore_wildcard_types.bal, openapi-cli/src/test/resources/expected_gen/without-data-binding-type.bal, openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java, openapi-integration-tests/src/test/resources/service/return/ballerina/multiple_mediatype_for_one_response_code.bal, openapi-integration-tests/src/test/resources/service/return/ballerina/response_has_inline_record.bal
> Related PR: https://github.com/ballerina-platform/openapi-tools/pull/1578
https://github.com/ballerina-platform/openapi-tools/pull/1602
Fix: https://github.com/ballerina-platform/ballerina-library/issues/5731
This fix will be available with the 2201.8.5 version onwards 
=> [master] Remove unused types from generated types.bal in service generation

ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/constraint/Constants.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/hateoas/Constants.java
=> Add missing license headers

gradle.properties
=> [1.8.x] Update Ballerina lang version

gradle.properties, openapi-bal-task-plugin/src/main/java/io/ballerina/openapi/bal/tool/OpenAPICodeGeneratorTool.java
$Subject 
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6198
=> [master] Update client integration for bal build with new plugin changes, reflecting changes in tool name implementation

openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/OpenApiConverterUtilsTest.java
> $Subject
Related to: https://github.com/ballerina-platform/ballerina-library/issues/6217
=> Disable escape identifier test in favour of lang change

ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/parameter/HeaderParameterMapper.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/parameter/PathParameterMapper.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/parameter/QueryParameterMapper.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/parameter/RequestBodyMapper.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/utils/MapperCommonUtils.java, gradle.properties, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/OpenApiConverterUtilsTest.java
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6217
=> Re-enable escape identifier test after lang changes

openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/parameter/HeaderParameterGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/parameter/PathParameterGenerator.java
=> [typegen]Refactor Header parameter in client generation

openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/GeneratorUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/TypeHandler.java, openapi-core/src/main/java/io/ballerina/openapi/core/service/ServiceGenerationUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/service/parameter/DefaultRequestBodyGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/service/parameter/LowResourceRequestBodyGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/service/parameter/RequestBodyGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/service/resource/LowResourceGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/service/response/DefaultReturnTypeGenerator.java
=> Add low resource request body generation and type inclusion generation

openapi-cli/src/test/java/io/ballerina/openapi/generators/client/EnumGenerationTests.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionBodyGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionReturnTypeGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/RemoteFunctionGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/RemoteFunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/ResourceFunctionGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/ResourceFunctionSingnatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/parameter/HeaderParameterGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/parameter/PathParameterGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/parameter/QueryParameterGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/TypeHandler.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/BallerinaTypesGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/PrimitiveTypeGenerator.java
=> [WIP]Enable enum tests

openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ServiceDiagnosticTests.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/GeneratorUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/TypeHandler.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/ArrayTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/TypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/service/parameter/QueryParameterGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/service/response/DefaultReturnTypeGenerator.java
=> Fix runtime issues when enabling service diagnostic tests

ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/hateoas/HateoasMapperImpl.java
> $subject
Fixes: [#6281](https://github.com/ballerina-platform/ballerina-library/issues/6281)
=> Fix logic issue in selecting the relevant HATEOAS resource when resource method is not configured

ballerina-to-openapi/build.gradle
Add publish task for grade to publish ballerina-openapi artifact into maven
=> Add publish task for grade to publish ballerina-openapi artifact into maven

openapi-cli/src/test/java/io/ballerina/openapi/generators/client/ResourceFunctionTests.java, openapi-cli/src/test/resources/generators/client/resource/ballerina/request_body.bal, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/TypeHandler.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/document/ClientDocCommentGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/document/DocCommentGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/document/ServiceDocCommentGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/service/ServiceDeclarationGenerator.java
=> [typegen]Add fix for service generation doc comments 

openapi-cli/src/test/java/io/ballerina/openapi/generators/client/AnnotationTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureNodeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureReturnTypeTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/AnnotationTests.java, openapi-cli/src/test/resources/generators/client/ballerina/deprecated_functions.bal, openapi-cli/src/test/resources/generators/client/ballerina/deprecated_mix_params.bal, openapi-cli/src/test/resources/generators/client/ballerina/display_and_deprecated.bal, openapi-cli/src/test/resources/generators/client/ballerina/request_body_allOf_scenarios.bal, openapi-cli/src/test/resources/generators/client/ballerina/return/no_content_type.bal, openapi-cli/src/test/resources/generators/schema/ballerina/deprecated_schemas.bal, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/RemoteFunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/ResourceFunctionSingnatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/parameter/HeaderParameterGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/parameter/RequestBodyGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/parameter/RequestBodyHeaderParameter.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/document/ClientDocCommentGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/document/DocCommentsGeneratorUtil.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/document/ServiceDocCommentGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/document/TypesDocCommentGenerator.java
=> [typegen] Fix header handling in requestBody and Adding deprecated doc comments to client and service generation

openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java, openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java, openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/ComparedGeneratedFileTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/PathParameterTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ServiceDiagnosticTests.java, openapi-cli/src/test/resources/expected_gen/constraint_import_types.bal, openapi-cli/src/test/resources/expected_gen/licenses/client.bal, openapi-cli/src/test/resources/expected_gen/licenses/schema.bal, openapi-cli/src/test/resources/expected_gen/non_constraint_import_types.bal, openapi-cli/src/test/resources/generators/client/ballerina/request_body_allOf_scenarios.bal, openapi-cli/src/test/resources/generators/client/ballerina/url_encoded_payload.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/api2pdf.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/description_with_special_characters.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/display_annotation.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/duplicated_response.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/format_types_v3_0.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/format_types_v3_1.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/header_with_enum.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/incorrect_format.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/multiline_param_comment.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/multiple_pathparam.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/nillable_response.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/nillable_union_response.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/openapi_weather_api.bal, openapi-cli/src/test/resources/generators/client/file_provider/ballerina/uber_openapi.bal, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionReturnTypeGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/parameter/RequestBodyGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/parameter/RequestBodyHeaderParameter.java
$Subject
remaining failing tests 
[CodeGeneratorTest](https://github.com/ballerina-platform/openapi-tools/compare/classes/io.ballerina.openapi.CodeGeneratorTest.html). [generateSkeleton](https://github.com/ballerina-platform/openapi-tools/compare/classes/io.ballerina.openapi.CodeGeneratorTest.html#generateSkeleton)
[CodeGeneratorTest](https://github.com/ballerina-platform/openapi-tools/compare/classes/io.ballerina.openapi.CodeGeneratorTest.html). [openApiToBallerinaCodeGenTest[5](petstore.yaml, petstore.bal)](https://github.com/ballerina-platform/openapi-tools/compare/classes/io.ballerina.openapi.CodeGeneratorTest.html#openApiToBallerinaCodeGenTest[5](petstore.yaml,%20petstore.bal))
[BallerinaCodeGeneratorLicenseTests](https://github.com/ballerina-platform/openapi-tools/compare/classes/io. …
=> [typegen] Enable client tests

openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java, openapi-cli/src/test/resources/generators/client/ballerina/return/no_content_type.bal
=> [typegen] Add client diagnostic

openapi-bal-task-plugin/src/main/java/io/ballerina/openapi/bal/tool/OpenAPICodeGeneratorTool.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ServiceGenerationHandler.java
=> Fix failing cmd tests

openapi-bal-task-plugin/src/main/java/io/ballerina/openapi/bal/tool/OpenAPICodeGeneratorTool.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/GeneratorUtils.java
=> Remove unused entity removing function

ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/ServiceMapperFactory.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/diagnostic/DiagnosticMessages.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/model/RequestParameter.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/model/RequestParameterInfo.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/model/ResponseInfo.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/pipeline/InterceptorPipeline.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/pipeline/RequestParameterCollector.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/pipeline/ResponseCollector.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/types/Interceptor.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/types/RequestErrorInterceptor.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/types/RequestInterceptor.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/types/Resource.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/types/ResponseErrorInterceptor.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/types/ResponseInterceptor.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/interceptor/types/TargetResource.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/parameter/DefaultParameterMapper.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/parameter/ParameterMapperWithInterceptors.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/response/DefaultResponseMapper.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/response/ResponseMapperWithInterceptors.java, ballerina-to-openapi/src/main/java/module-info.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/InterceptorTests.java
=> [sync] Sync back-master with master 

.github/workflows/pull-request.yml, gradle.properties, openapi-client-native/ballerina-tests/Dependencies.toml
- Remove redundant push in pull request workflow
- Update dependency version
=> [master] Update dependency versions

openapi-cli/src/test/java/io/ballerina/openapi/generators/client/NoServerURLTest.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/QueryParameterTests.java, openapi-cli/src/test/resources/expected_gen/licenses/utils_for_both_service_client_generation.bal, openapi-cli/src/test/resources/expected_gen/licenses/utils_for_client_generation.bal, openapi-cli/src/test/resources/expected_gen/licenses/utils_for_with_user_given_license.bal, openapi-cli/src/test/resources/expected_gen/utils.bal, openapi-cli/src/test/resources/generators/client/ballerina/blank_value_server_url.bal, openapi-cli/src/test/resources/generators/client/ballerina/default_util.bal, openapi-cli/src/test/resources/generators/client/ballerina/query_param_with_content_value.bal, openapi-cli/src/test/resources/generators/client/swagger/blank_value_server_url.yaml, openapi-cli/src/test/resources/generators/client/swagger/query_param_with_content_value.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/BallerinaClientGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionBodyGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/ResourceFunctionGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/ResourceFunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/ServerURLGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/diagnostic/DiagnosticMessages.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/parameter/HeaderParameterGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/parameter/QueryParameterGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/ErrorMessages.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/GeneratorUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/diagnostic/CommonDiagnosticMessages.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/resource/DefaultResourceGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/resource/LowResourceGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/BallerinaTypesGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/diagnostic/TypeGenerationDiagnosticMessages.java, openapi-core/src/main/resources/templates/utils_openapi.bal
- bug: serverURL value assigned in the tests generation
- inconsistency behaviour for resource / remote functions when the path parameter has an unsupported  type in client generation (fix: it will skip function generation for operation)
- fix the diagnostic logger issue in the relative path generation
Fixes below error
- https://github.com/ballerina-platform/ballerina-library/issues/5812
- https://github.com/ballerina-platform/ballerina-library/issues/6075
- https://github.com/ballerina-platform/ballerina-library/issues/4822
- https://github.com/ballerina-platform/ballerina-library/issues/4887
- https://github.com/ballerina-platform/ballerina-library/issues/4879
=> [client] Fix inconsistencies found with RC testing

openapi-bal-task-plugin/src/main/java/io/ballerina/openapi/bal/tool/OpenAPICodeGeneratorTool.java, openapi-cli/src/main/resources/cli-help/ballerina-openapi-add.help, openapi-cli/src/main/resources/cli-help/ballerina-openapi.help
=> Update help texts for OpenAPI tool

.gitignore, build.gradle, openapi-bal-task-plugin/src/main/java/io/ballerina/openapi/bal/tool/OpenAPICodeGeneratorTool.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/BaseCmd.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/OpenApiCmd.java, openapi-cli/src/main/resources/cli-help/ballerina-openapi-add.help, openapi-cli/src/main/resources/cli-help/ballerina-openapi.help, openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionReturnTypeGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionStatusCodeReturnTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/ImplFunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/RemoteExternalFunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/RemoteFunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/ResourceExternalFunctionGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/ResourceExternalFunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/ResourceFunctionGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/ResourceFunctionSignatureGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/diagnostic/ClientDiagnosticImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/diagnostic/DiagnosticMessages.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/ClientGenerationTests.java
> $Subject
- Changed the file name which is used to get the client native version
- Changed the status code binding option name: `--with-status-code-binding` -> `--status-code-binding`
- Add a warning when skipping `default` response in the operation with status code binding option
=> Add changes from the team meeting

openapi-cli/src/main/java/io/ballerina/openapi/cmd/OpenApiCmd.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/client/FunctionSignatureReturnTypeTests.java, openapi-cli/src/test/resources/generators/client/ballerina/deprecated_mix_params.bal, openapi-cli/src/test/resources/generators/client/ballerina/return/return_type_encode.bal, openapi-cli/src/test/resources/generators/client/ballerina/vendor_specific_with_subtype.bal, openapi-cli/src/test/resources/generators/client/swagger/return_type/return_type_encoding.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionReturnTypeGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/GeneratorUtils.java
> Fixes 
- https://github.com/ballerina-platform/ballerina-library/issues/6343
- https://github.com/ballerina-platform/ballerina-library/issues/5113
> List all JDK versions, operating systems, databases, and browser/versions on …
=> [master]Fix for response with encoding media type in client generation

ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/Constants.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/GeneratorUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/TypeHandler.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/BallerinaTypesGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/TypeGeneratorUtils.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/AllOfRecordTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/AnyDataTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/ArrayTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/EnumGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/PrimitiveTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/RecordTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/ReferencedTypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/TypeGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/UnionTypeGenerator.java
$subject
Additional this fixes `205` status code name …
=> Return `anydata` for multiple union types with `anydata` type

gradle.properties, openapi-bal-task-plugin/src/main/java/io/ballerina/openapi/bal/tool/Constants.java, openapi-bal-task-plugin/src/main/java/io/ballerina/openapi/bal/tool/OpenAPICodeGeneratorTool.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/BallerinaCodeGenerator.java, openapi-client-native/ballerina-tests/client.bal, openapi-client-native/ballerina-tests/service.bal, openapi-client-native/ballerina-tests/tests/test.bal, openapi-client-native/ballerina-tests/types.bal
> $Subject
Lang change PR: https://github.com/ballerina-platform/ballerina-lang/pull/42573
=> Address the the client external function call changes from runtime

openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/RecordDefaultValueTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/default_non_required_field_schema.bal, openapi-cli/src/test/resources/generators/schema/swagger/default_non_required_field_schema.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/RecordTypeGenerator.java
$subject
Fixes https://github.com/ballerina-platform/ballerina-library/issues/5839 …
=> Add default values to record fields

gradle.properties, openapi-client-native/ballerina-tests/client.bal, openapi-client-native/ballerina-tests/tests/test.bal, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/AuthConfigGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/AuthConfigGeneratorWithStatusCodeBinding.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/BallerinaClientGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/BallerinaClientGeneratorWithStatusCodeBinding.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/BallerinaTestGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/GeneratorConstants.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/ClientGenerationTests.java, openapi-integration-tests/src/test/resources/client/project-04/Ballerina.toml, openapi-integration-tests/src/test/resources/client/project-04/openapi.yaml, openapi-integration-tests/src/test/resources/client/project-expected/client_remote.bal
> $Subject
Addressing the changes done via https://github.com/ballerina-platform/module-ballerina-http/pull/1954
=> Add the client name change from the HTTP module

openapi-core/src/main/java/io/ballerina/openapi/core/generators/constraint/ConstraintDiagnosticMessages.java
=> [master] Fix for RC1 pack

openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/AllOfRecordTypeGenerator.java
=> [master]Fix NPE issue in client code generation in GitHub connector

openapi-cli/src/test/java/io/ballerina/openapi/generators/common/DocCommenTests.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/GeneratorUtils.java
>  Fixes: Doc comment override issue
=> [master]Fix doc comment override issue

openapi-bal-task-plugin/src/main/java/io/ballerina/openapi/bal/tool/OpenAPICodeGeneratorTool.java
=> [master]Fix tag and operation filter issue in client generation in bal build 

.github/workflows/build-timestamped-master.yml
=> Disable codecov step temporarily

build.gradle, gradle.properties
=> Add `createProperties` as a dependency to release task

ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/Constants.java, module-ballerina-openapi/annotation.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_1/service.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_2/service.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_5/service.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_6/service.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_8/service.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_9/service.bal, openapi-integration-tests/src/test/resources/build/project_2/service.bal, openapi-integration-tests/src/test/resources/build/project_3/service.bal
> Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6478
https://github.com/ballerina-platform/ballerina-library/issues/6484
=> [master] Remove quoted from version field in openapi annotation

ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/Constants.java, module-ballerina-openapi/annotation.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_1/service.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_2/service.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_5/service.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_6/service.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_8/service.bal, openapi-integration-tests/src/test/resources/ballerina_sources/project_9/service.bal, openapi-integration-tests/src/test/resources/build/project_2/service.bal, openapi-integration-tests/src/test/resources/build/project_3/service.bal
> Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6478
https://github.com/ballerina-platform/ballerina-library/issues/6484
Relevant PRs: https://github.com/ballerina-platform/openapi-tools/pull/1709
=> [2.0.x] Remove quoted from version field in openapi annotation

gradle.properties
=> [2.0.x] Update Http verison 

gradle.properties, module-ballerina-openapi/annotation.bal, openapi-client-native/ballerina-tests/Dependencies.toml
=> [2.0.x] Update ballerina lang and http versions

.github/workflows/central-publish.yml, gradle.properties, module-ballerina-openapi/annotation.bal
=> [2.0.x] Add the workaround for openapi resource annotation data binding issue 

.github/workflows/central-publish.yml
=> [master] Update workflow for removing snapshot for dev and stage in central

gradle.properties, openapi-client-native/build.gradle
=> Fix client native publish issues

gradle.properties, openapi-client-native/build.gradle
=> [2.0.x] Fix client native publish issues

gradle.properties, openapi-client-native/build.gradle
> $Subject
Additionally, disabled the client native publish
=> [2.0.x] Fix issues with WSO2 nexus release

gradle.properties, openapi-client-native/build.gradle
=> Fix issues with WSO2 nexus release

openapi-cli/src/test/java/io/ballerina/openapi/generators/auth/MixedApiKeyAndHTTPAuthTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestConstants.java, openapi-cli/src/test/resources/expected_gen/petstore_catch_all_path_client.bal, openapi-cli/src/test/resources/expected_gen/petstore_client_swagger.bal, openapi-cli/src/test/resources/generators/client/ballerina/combination_of_apikey_and_http_oauth.bal, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/AuthConfigGeneratorImp.java
>  Fixes https://github.com/ballerina-platform/ballerina-library/issues/6655
=> [2.0.x]Fix authentication configs issue in client generation

openapi-cli/src/test/java/io/ballerina/openapi/generators/auth/MixedApiKeyAndHTTPAuthTests.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/common/TestConstants.java, openapi-cli/src/test/resources/expected_gen/petstore_catch_all_path_client.bal, openapi-cli/src/test/resources/expected_gen/petstore_client_swagger.bal, openapi-cli/src/test/resources/generators/client/ballerina/combination_of_apikey_and_http_oauth.bal, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/AuthConfigGeneratorImp.java
>  Fixes https://github.com/ballerina-platform/ballerina-library/issues/6655
=> Fix authentication configs issue in client generation

gradle.properties
=> [2.0.x] Update ballerina lang version

ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/Constants.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/ServiceToOpenAPIMapper.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/diagnostic/DiagnosticMessages.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/metainfo/MetaInfoMapper.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/metainfo/MetaInfoMapperImpl.java, ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/metainfo/ResourceMetaInfoAnnotation.java, gradle.properties, module-ballerina-openapi/annotation.bal, openapi-validator/src/test/java/io/ballerina/openapi/validator/tests/ReturnTypeValidationTests.java
>  https://github.com/ballerina-platform/ballerina-library/issues/5983
This PR is mainly contains two fixes :
- Support reference **JSON** example file path for the example
- Support **request body** example mapping for OAS
Integration tests and unit tests will be added via separate PRs
=> [master]Add example improvements

.github/workflows/build-ballerina-to-openapi.yml
=> Update workflow display name

openapi-bal-task-plugin/src/main/java/io/ballerina/openapi/bal/tool/OpenAPICodeGeneratorTool.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/OpenApiCmd.java, openapi-client-native/ballerina-tests/Ballerina.toml, openapi-client-native/build-configs/resources/Ballerina.toml
> $Subject
Incorporating this improvement into the tool: 
- https://github.com/ballerina-platform/ballerina-lang/issues/42466
=> Add `graalvmCompatible` flag to client native dependency

gradle.properties, openapi-client-native/ballerina-tests/Dependencies.toml
=> [master]Update dependency versions for update 10

ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/metainfo/MetaInfoMapperImpl.java, openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ExampleTests.java, openapi-cli/src/test/resources/ballerina-to-openapi/metainfo/examples/example.json, openapi-cli/src/test/resources/ballerina-to-openapi/metainfo/examples/resource_annotation_examples.bal, openapi-cli/src/test/resources/ballerina-to-openapi/metainfo/examples/resource_annotation_examples.yaml, openapi-cli/src/test/resources/generators/client/mock/reference_example.bal, openapi-cli/src/test/resources/testng.xml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mock/AdvanceMockClientGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mock/BallerinaMockClientGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/GeneratorConstants.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/OASModifier.java
> 
1. uninitialized field 'apiKeyConfig' issue in client mock generation
2. example resolution with commented line
=> [master]Fix some regression issues in RC1 pack

openapi-core/src/main/java/io/ballerina/openapi/core/generators/service/ServiceGenerationHandler.java
=> Fix service contract generation with single file

gradle.properties, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/OASModifier.java
=> Update dependencies for RC2

gradle.properties
=> Update ballerina to openapi version

openapi-core/build.gradle
=> Publish Ballerina OpenAPI core library to GitHub

gradle.properties, openapi-client-native/ballerina-tests/Dependencies.toml
=> [2.1.x]Update lang version

gradle.properties
=> [2.1.x]Update gradle.properties with tool version

gradle.properties
=> [2.1.x]Update versions for gradle.properties for u10

gradle.properties
=> [2.0.x]Update version for U9 patch

gradle.properties, gradle/wrapper/gradle-wrapper.properties, module-ballerina-openapi/build.gradle, openapi-client-native/ballerina-tests/Ballerina.toml, openapi-client-native/ballerina-tests/Dependencies.toml
=> Update dependency versions for U11

gradle.properties
=> Update xml version

gradle.properties
=> Update commons-io version

module-ballerina-openapi/README.md
Purpose of this PR is to update the `README.md` which was previously `Module.md` (The default package documentation), by including the service level, resource level, and example annotations.
Also the details regarding the Validator Compiler Plugin has also been removed since we no longer encourage users to use it.
Fixes: [#7504](https://github.com/ballerina-platform/ballerina-library/issues/7504)
> Summary of user stories …
=> Update `README.md` with service level, resource level, and example annotations

openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/OASModifier.java
=> Fix NPE when aligning request body

docs/ballerina-to-oas/spec/spec.md
=> Fix formatting

gradle.properties
=> Update ballerina to oas package version

ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/ServersMapperImpl.java, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/record_field_with_name_annotation.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/record_with_default_values.yaml, openapi-cli/src/test/resources/ballerina-to-openapi/expected_gen/record/with_read_only_keyword.yaml, openapi-integration-tests/src/test/resources/ballerina_sources/project_openapi_info_with_service_contract_type/result.yaml
> $Subject
When we cannot extract the port details from the listener, we are defaulting the port to the default port - `9090`
=> Add default listener when we cannot extract the listener info

openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/ConstraintTests.java, openapi-cli/src/test/resources/generators/schema/ballerina/constraint/integer_constraint_with_decimal_values.bal, openapi-cli/src/test/resources/generators/schema/swagger/constraint/integer_constraint_with_decimal_values.yaml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/mime/UrlEncodedType.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/constraint/ConstraintGeneratorImp.java
> $subject
Related issue: https://github.com/ballerina-platform/ballerina-library/issues/7821 …
=> Fix constraint generation for integer fields with decimal values in OpenAPI spec

openapi-core/src/main/java/io/ballerina/openapi/core/generators/document/ClientDocCommentGenerator.java
> $subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7354 …
=> Generate API docs for the resource functions with special char prefixes

openapi-cli/src/main/java/io/ballerina/openapi/cmd/Align.java, openapi-cli/src/main/resources/cli-help/ballerina-openapi-align.help
> $subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7824 …
=> Change the `align` option names to `--include` and `--exclude`

openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/OASModifier.java
=> Fix common path extraction logic

gradle.properties, module-ballerina-openapi/Ballerina.toml, module-ballerina-openapi/CompilerPlugin.toml, openapi-build-extension/src/main/java/io/ballerina/openapi/build/HttpServiceAnalysisTask.java, openapi-cli/src/main/java/io/ballerina/openapi/cmd/Align.java, openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/BuildExtensionTests.java
> $subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7943 …
=> Skip test sources during OpenAPI export to prevent spec overwriting

openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java, openapi-cli/src/test/resources/bal_name_ext.yaml, openapi-cli/src/test/resources/bal_name_ext_sanitized.yaml, openapi-cli/src/test/resources/expected_gen/bal_name_ext_client.bal, openapi-cli/src/test/resources/expected_gen/bal_name_ext_sanitized_client.bal, openapi-cli/src/test/resources/expected_gen/bal_name_ext_service_contract.bal, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/AuthConfigGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionBodyGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/document/TypesDocCommentGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/RecordTypeGenerator.java
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/8059
=> [2201.12.x] Fix handling type or field names matching Ballerina key words

openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java, openapi-cli/src/test/resources/bal_name_ext.yaml, openapi-cli/src/test/resources/bal_name_ext_sanitized.yaml, openapi-cli/src/test/resources/expected_gen/bal_name_ext_client.bal, openapi-cli/src/test/resources/expected_gen/bal_name_ext_sanitized_client.bal, openapi-cli/src/test/resources/expected_gen/bal_name_ext_service_contract.bal, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/AuthConfigGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/client/FunctionBodyGeneratorImp.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/document/TypesDocCommentGenerator.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/type/generators/RecordTypeGenerator.java
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/8059
=> Fix handling type or field names matching Ballerina key words

openapi-integration-tests/src/test/java/io/ballerina/openapi/TestUtil.java
> This is to fix the build failure here
https://github.com/ballerina-platform/openapi-tools/actions/runs/17817021685/job/50652282693#step:6:3816
=> Strip redundant part in the version of the tool push command

ballerina-to-openapi/src/main/java/io/ballerina/openapi/service/mapper/type/extension/BallerinaTypeExtensioner.java
Unsupported types(like singletons which are not yet supported) will have a null schema which is causing this issue
> $Subject
=> Fix NPE in the extension generator due to unsupported type schemas

module-ballerina-openapi/Dependencies.toml, openapi-cli/src/test/java/io/ballerina/openapi/CodeGeneratorTest.java, openapi-cli/src/test/java/io/ballerina/openapi/cmd/OpenAPICmdTest.java, openapi-cli/src/test/resources/cmd/flatten/allof_openapi.yaml, openapi-cli/src/test/resources/cmd/flatten/flattened_allof_openapi_expected.yaml, openapi-client-native/ballerina-tests/Dependencies.toml, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/InlineModelResolver.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/OASModifier.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/TypeFixer.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/TypeHandler.java, openapi-core/src/main/java/io/ballerina/openapi/core/generators/common/diagnostic/CommonDiagnosticMessages.java, openapi-tool/Dependencies.toml
> $Subject
Fixes:
- [Redeclared variable error](https://github.com/ballerina-platform/ballerina-library/issues/8025)
- Annotations not passed to fields which are defined in the included records
- [Aligned names with numeric values](https://github.com/ballerina-platform/ballerina-library/issues/8011)
=> Fix high priority bugs
